//! Mapping between cimoxide's decoded identifiers and RDF IRIs.
//!
//! The decoder is namespace-blind by construction: `local_name()` drops the XML prefix and
//! `strip_fragment()` drops the IRI base, so `Element::fields` keys are bare
//! `IdentifiedObject.name` strings and `rdf:resource` targets have lost their namespace.
//! Everything needed to put that back is in the CGMES schema — each class's and attribute's
//! namespace, a literal's XSD type, an enumeration's value namespace — generated by `cimgen`
//! or read from RDFS at runtime; this module is the lookup layer over it.

use std::collections::HashMap;
use std::sync::OnceLock;

use cimmodel::base::{AttrKind, Schema};
use cimmodel::registry::type_registry;

const XSD: &str = "http://www.w3.org/2001/XMLSchema#";

fn schema() -> &'static Schema {
    type_registry().schema("cgmes").expect("the CGMES family is registered")
}

/// Base for identifiers that are neither absolute IRIs nor UUIDs. Nothing in the CGMES test
/// configurations hits this, but `rdf:ID` is not required to be a UUID.
pub const LOCAL_BASE: &str = "http://cimoxide/id/";

/// Namespace used for predicates whose attribute id is absent from the schema — a
/// third-party extension, or a CIM version skew between the data and the generated schema.
pub const FALLBACK_NS: &str = "http://iec.ch/TC57/CIM100#";

/// What kind of RDF object an attribute's value denotes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    /// A literal, typed by `AttrRdf::range`.
    Literal,
    /// An IRI reference to another CIM object.
    Association,
    /// An IRI naming an enumeration value; `AttrRdf::range` is the enum's namespace.
    Enum,
}

/// An attribute's RDF form, resolved from the schema.
#[derive(Debug, Clone, Copy)]
pub struct AttrRdf {
    pub namespace: &'static str,
    /// XSD datatype IRI for [`Kind::Literal`], the enum namespace for [`Kind::Enum`],
    /// empty for [`Kind::Association`].
    pub range: &'static str,
    pub kind: Kind,
}

// Consulted once per field of every element, so indexed once: by class name, and by
// attribute id (an id names one predicate, whichever class declares it — the first in
// table order).
fn type_ns_index() -> &'static HashMap<&'static str, &'static str> {
    static IDX: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();
    IDX.get_or_init(|| {
        schema().classes.iter().filter(|c| !c.ns.is_empty()).map(|c| (c.local, c.ns)).collect()
    })
}

fn attr_index() -> &'static HashMap<&'static str, AttrRdf> {
    static IDX: OnceLock<HashMap<&'static str, AttrRdf>> = OnceLock::new();
    IDX.get_or_init(|| {
        // The full XSD IRIs, one per datatype the schema uses.
        let mut xsd: HashMap<&'static str, &'static str> = HashMap::new();
        let mut idx = HashMap::new();
        for a in schema().classes.iter().flat_map(|c| c.attrs).filter(|a| !a.ns.is_empty()) {
            let (kind, range) = match a.kind {
                AttrKind::Literal => {
                    let iri = *xsd
                        .entry(a.xsd)
                        .or_insert_with(|| Box::leak(format!("{XSD}{}", a.xsd).into_boxed_str()));
                    (Kind::Literal, iri)
                }
                AttrKind::Enum => (Kind::Enum, a.value_ns),
                AttrKind::Association => (Kind::Association, ""),
            };
            idx.entry(a.id).or_insert(AttrRdf { namespace: a.ns, range, kind });
        }
        idx
    })
}

/// RDF namespace IRI of a CIM class, e.g. `http://iec.ch/TC57/CIM100-European#` for
/// `BoundaryPoint`. Trailing `#` included.
pub fn type_namespace(type_name: &str) -> Option<&'static str> {
    type_ns_index().get(type_name).copied()
}

/// Full class IRI for a decoded `type_name`.
pub fn type_iri(type_name: &str) -> String {
    format!("{}{type_name}", type_namespace(type_name).unwrap_or(FALLBACK_NS))
}

/// RDF metadata for an `Element::fields` key such as `"ACLineSegment.b0ch"`.
pub fn attr(attr_id: &str) -> Option<AttrRdf> {
    attr_index().get(attr_id).copied()
}

/// Full predicate IRI for an `Element::fields` key.
pub fn predicate_iri(attr_id: &str) -> String {
    let ns = attr(attr_id).map_or(FALLBACK_NS, |a| a.namespace);
    format!("{ns}{attr_id}")
}

fn is_absolute_iri(s: &str) -> bool {
    // scheme = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." ) ":"
    let mut chars = s.char_indices();
    match chars.next() {
        Some((_, c)) if c.is_ascii_alphabetic() => {}
        _ => return false,
    }
    for (i, c) in chars {
        match c {
            ':' => return i > 0,
            c if c.is_ascii_alphanumeric() || c == '+' || c == '-' || c == '.' => {}
            _ => return false,
        }
    }
    false
}

fn is_uuid(s: &str) -> bool {
    let b = s.as_bytes();
    if b.len() != 36 {
        return false;
    }
    b.iter().enumerate().all(|(i, &c)| {
        if matches!(i, 8 | 13 | 18 | 23) {
            c == b'-'
        } else {
            c.is_ascii_hexdigit()
        }
    })
}

/// Subject IRI for a decoded MRID.
///
/// The decoder yields identifiers in two shapes: `_bd8b27aa-…` (from `rdf:ID`, and the form
/// `rdf:resource="#_…"` targets are stripped to) and `urn:uuid:2b6b90c0-…` (from `rdf:about`
/// on `md:FullModel`). Both normalise onto the CGMES-canonical `urn:uuid:` form, which is
/// what makes [`iri_to_mrid`] a pure inverse — no side table is held.
pub fn mrid_to_iri(mrid: &str) -> String {
    if is_absolute_iri(mrid) {
        return mrid.to_string();
    }
    let bare = mrid.strip_prefix('_').unwrap_or(mrid);
    if is_uuid(bare) {
        format!("urn:uuid:{bare}")
    } else {
        format!("{LOCAL_BASE}{mrid}")
    }
}

/// Inverse of [`mrid_to_iri`], resolved against the dataset the IRI came from.
///
/// `urn:uuid:X` is ambiguous on its own — the decoder may hold it as `_X` or as `X` — so
/// membership in `entries` picks the right one.
pub fn iri_to_mrid(iri: &str, ds: &cimmodel::CimDataset) -> Option<String> {
    if let Some(rest) = iri.strip_prefix(LOCAL_BASE) {
        return ds.entries.contains_key(rest).then(|| rest.to_string());
    }
    if let Some(uuid) = iri.strip_prefix("urn:uuid:") {
        let underscored = format!("_{uuid}");
        if ds.entries.contains_key(&underscored) {
            return Some(underscored);
        }
        if ds.entries.contains_key(uuid) {
            return Some(uuid.to_string());
        }
    }
    ds.entries.contains_key(iri).then(|| iri.to_string())
}

/// Object IRI for an association value.
///
/// Association targets are normally MRIDs, but two `eu:`-namespaced enumerations
/// (`LimitKind`, `SVCControlMode`) are generated as marker structs rather than enums —
/// upstream `cims:stereotype` parsing is last-write-wins and their `European` stereotype
/// overwrites the `enumeration` one — so `eu:OperationalLimitType.kind` arrives here as a
/// plain reference holding a fragment-stripped `LimitKind.patl`. A value that names no entry
/// in the dataset but does match a known `Type.value` is that case, and the class namespace
/// rebuilds the IRI the decoder discarded.
pub fn reference_iri(value: &str, ds: &cimmodel::CimDataset) -> String {
    if !ds.entries.contains_key(value)
        && let Some((type_name, _)) = value.split_once('.')
        && let Some(ns) = type_namespace(type_name)
    {
        return format!("{ns}{value}");
    }
    mrid_to_iri(value)
}

/// Namespace bindings for queries: every namespace the CGMES schema binds, plus `xsd:`.
pub fn sparql_prefixes() -> &'static [(&'static str, &'static str)] {
    static P: OnceLock<Vec<(&'static str, &'static str)>> = OnceLock::new();
    P.get_or_init(|| {
        let mut v: Vec<(&'static str, &'static str)> = schema().namespaces.to_vec();
        v.push(("xsd", XSD));
        v
    })
}
