[package]
name = "cimoxide-cli"
version = "0.0.4"
edition = "2024"

[[bin]]
name = "cimcli"
path = "src/main.rs"

[dependencies]
cimdecoder     = { path = "../cimdecoder" }
cimstructs     = { path = "../cimstructs" }
cimvalidation  = { path = "../cimvalidation" }
serde_json     = "1"
quick-xml      = { version = "0.37", features = ["encoding"] }

[dev-dependencies]
cimdecoder  = { path = "../cimdecoder" }
cimstructs  = { path = "../cimstructs" }
