/// Simplified boiler and steam turbine with PID governor.
#[derive(Debug, Default, Clone, serde::Serialize, serde::Deserialize)]
pub struct GovSteamEU {
    #[serde(flatten)]
    pub base: super::TurbineGovernorDynamics,
    /// Control valves rate closing limit (Chc). Unit = PU / s. Typical value = -3,3.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub chc: Option<f64>,
    /// Control valves rate opening limit (Cho). Unit = PU / s. Typical value = 0,17.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cho: Option<f64>,
    /// Intercept valves rate closing limit (Cic). Typical value = -2,2.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cic: Option<f64>,
    /// Intercept valves rate opening limit (Cio). Typical value = 0,123.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cio: Option<f64>,
    /// Deadband of the frequency corrector (db1). Typical value = 0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub db1: Option<f64>,
    /// Deadband of the speed governor (db2). Typical value = 0,0004.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub db2: Option<f64>,
    /// Maximum control valve position (Hhpmax). Typical value = 1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hhpmax: Option<f64>,
    /// Gain of the power controller (Ke). Typical value = 0,65.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ke: Option<f64>,
    /// Gain of the frequency corrector (Kfcor). Typical value = 20.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kfcor: Option<f64>,
    /// Fraction of total turbine output generated by HP part (Khp). Typical value = 0,277.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub khp: Option<f64>,
    /// Fraction of total turbine output generated by HP part (Klp). Typical value = 0,723.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub klp: Option<f64>,
    /// Gain of the speed governor (Kwcor). Typical value = 20.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub komegacor: Option<f64>,
    /// Base for power values (MWbase) (> 0). Unit = MW.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mwbase: Option<f64>,
    /// Maximal active power of the turbine (Pmax). Typical value = 1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pmax: Option<f64>,
    /// Maximum low pressure limit (Prhmax). Typical value = 1,4.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prhmax: Option<f64>,
    /// Intercept valves transfer limit (Simx). Typical value = 0,425.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub simx: Option<f64>,
    /// Boiler time constant (Tb) (>= 0). Typical value = 100.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tb: Option<f64>,
    /// Derivative time constant of the power controller (Tdp) (>= 0). Typical value = 0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tdp: Option<f64>,
    /// Electro hydraulic transducer (Ten) (>= 0). Typical value = 0,1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ten: Option<f64>,
    /// Frequency transducer time constant (Tf) (>= 0). Typical value = 0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tf: Option<f64>,
    /// Time constant of the power controller (Tfp) (>= 0). Typical value = 0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tfp: Option<f64>,
    /// High pressure (HP) time constant of the turbine (Thp) (>= 0). Typical value = 0,31.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thp: Option<f64>,
    /// Integral time constant of the power controller (Tip) (>= 0). Typical value = 2.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tip: Option<f64>,
    /// Low pressure (LP) time constant of the turbine (Tlp) (>= 0). Typical value = 0,45.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tlp: Option<f64>,
    /// Power transducer time constant (Tp) (>= 0). Typical value = 0,07.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tp: Option<f64>,
    /// Reheater time constant of the turbine (Trh) (>= 0). Typical value = 8.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trh: Option<f64>,
    /// Control valves servo time constant (Tvhp) (>= 0). Typical value = 0,1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tvhp: Option<f64>,
    /// Intercept valves servo time constant (Tvip) (>= 0). Typical value = 0,15.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tvip: Option<f64>,
    /// Speed transducer time constant (Tw) (>= 0). Typical value = 0,02.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tw: Option<f64>,
    /// Upper limit for frequency correction (Wfmax) (> GovSteamEU.wfmin). Typical value = 0,05.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wfmax: Option<f64>,
    /// Lower limit for frequency correction (Wfmin) (< GovSteamEU.wfmax). Typical value = -0,05.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wfmin: Option<f64>,
    /// Emergency speed control lower limit (wmax1). Typical value = 1,025.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wmax1: Option<f64>,
    /// Emergency speed control upper limit (wmax2). Typical value = 1,05.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wmax2: Option<f64>,
    /// Upper limit for the speed governor (Wwmax) (> GovSteamEU.wwmin). Typical value = 0,1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wwmax: Option<f64>,
    /// Lower limit for the speed governor frequency correction (Wwmin) (< GovSteamEU.wwmax). Typical value = -1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wwmin: Option<f64>,
}
impl crate::base::CimElement for GovSteamEU {
    fn mrid(&self) -> &str { &self.base.base.base.id }
    fn type_name(&self) -> &'static str { "GovSteamEU" }
    fn as_any(&self) -> &dyn std::any::Any { self }
    fn to_json_value(&self) -> serde_json::Value {
        serde_json::to_value(self).unwrap_or(serde_json::Value::Null)
    }
    fn to_block(&self) -> crate::base::RdfBlock {
        let mut block = self.base.to_block();
        block.type_name = "GovSteamEU".to_string();
        if let Some(v) = self.chc {
            block.fields.insert("GovSteamEU.chc".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.cho {
            block.fields.insert("GovSteamEU.cho".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.cic {
            block.fields.insert("GovSteamEU.cic".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.cio {
            block.fields.insert("GovSteamEU.cio".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.db1 {
            block.fields.insert("GovSteamEU.db1".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.db2 {
            block.fields.insert("GovSteamEU.db2".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.hhpmax {
            block.fields.insert("GovSteamEU.hhpmax".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.ke {
            block.fields.insert("GovSteamEU.ke".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.kfcor {
            block.fields.insert("GovSteamEU.kfcor".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.khp {
            block.fields.insert("GovSteamEU.khp".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.klp {
            block.fields.insert("GovSteamEU.klp".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.komegacor {
            block.fields.insert("GovSteamEU.komegacor".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.mwbase {
            block.fields.insert("GovSteamEU.mwbase".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.pmax {
            block.fields.insert("GovSteamEU.pmax".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.prhmax {
            block.fields.insert("GovSteamEU.prhmax".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.simx {
            block.fields.insert("GovSteamEU.simx".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tb {
            block.fields.insert("GovSteamEU.tb".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tdp {
            block.fields.insert("GovSteamEU.tdp".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.ten {
            block.fields.insert("GovSteamEU.ten".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tf {
            block.fields.insert("GovSteamEU.tf".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tfp {
            block.fields.insert("GovSteamEU.tfp".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.thp {
            block.fields.insert("GovSteamEU.thp".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tip {
            block.fields.insert("GovSteamEU.tip".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tlp {
            block.fields.insert("GovSteamEU.tlp".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tp {
            block.fields.insert("GovSteamEU.tp".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.trh {
            block.fields.insert("GovSteamEU.trh".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tvhp {
            block.fields.insert("GovSteamEU.tvhp".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tvip {
            block.fields.insert("GovSteamEU.tvip".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tw {
            block.fields.insert("GovSteamEU.tw".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.wfmax {
            block.fields.insert("GovSteamEU.wfmax".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.wfmin {
            block.fields.insert("GovSteamEU.wfmin".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.wmax1 {
            block.fields.insert("GovSteamEU.wmax1".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.wmax2 {
            block.fields.insert("GovSteamEU.wmax2".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.wwmax {
            block.fields.insert("GovSteamEU.wwmax".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.wwmin {
            block.fields.insert("GovSteamEU.wwmin".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        block
    }
}

impl GovSteamEU {
    pub fn from_block(b: &crate::base::RdfBlock) -> Self {
        let mut obj = Self::default();
        obj.base.base.base.id.clone_from(&b.mrid);
        for (key, val) in &b.fields {
            match key.as_str() {
                "GovSteamEU.chc" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.chc = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.chc = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.cho" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.cho = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.cho = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.cic" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.cic = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.cic = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.cio" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.cio = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.cio = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.db1" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.db1 = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.db1 = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.db2" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.db2 = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.db2 = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.hhpmax" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.hhpmax = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.hhpmax = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.ke" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.ke = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.ke = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.kfcor" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.kfcor = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.kfcor = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.khp" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.khp = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.khp = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.klp" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.klp = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.klp = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.komegacor" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.komegacor = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.komegacor = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.mwbase" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.mwbase = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.mwbase = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.pmax" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.pmax = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.pmax = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.prhmax" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.prhmax = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.prhmax = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.simx" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.simx = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.simx = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.tb" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tb = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tb = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.tdp" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tdp = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tdp = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.ten" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.ten = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.ten = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.tf" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tf = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tf = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.tfp" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tfp = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tfp = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.thp" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.thp = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.thp = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.tip" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tip = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tip = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.tlp" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tlp = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tlp = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.tp" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tp = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tp = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.trh" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.trh = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.trh = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.tvhp" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tvhp = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tvhp = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.tvip" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tvip = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tvip = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.tw" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tw = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tw = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.wfmax" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.wfmax = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.wfmax = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.wfmin" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.wfmin = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.wfmin = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.wmax1" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.wmax1 = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.wmax1 = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.wmax2" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.wmax2 = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.wmax2 = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.wwmax" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.wwmax = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.wwmax = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamEU.wwmin" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.wwmin = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.wwmin = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "TurbineGovernorDynamics.AsynchronousMachineDynamics" => {
                    if let crate::base::FieldValue::Resource(sv) = val {
                        obj.base.asynchronous_machine_dynamics = Some(crate::base::MridRef { mrid: sv.clone() });
                    }
                }
                "TurbineGovernorDynamics.SynchronousMachineDynamics" => {
                    if let crate::base::FieldValue::Resource(sv) = val {
                        obj.base.synchronous_machine_dynamics = Some(crate::base::MridRef { mrid: sv.clone() });
                    }
                }
                "DynamicsFunctionBlock.enabled" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { obj.base.base.enabled = Some(sv.trim() == "true"); }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { obj.base.base.enabled = Some(sv.trim() == "true"); }
                        }
                        _ => {}
                    }
                }
                "IdentifiedObject.description" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { obj.base.base.base.description = sv.clone(); }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { obj.base.base.base.description = sv.clone(); }
                        }
                        _ => {}
                    }
                }
                "IdentifiedObject.energyIdentCodeEic" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { obj.base.base.base.energy_ident_code_eic = sv.clone(); }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { obj.base.base.base.energy_ident_code_eic = sv.clone(); }
                        }
                        _ => {}
                    }
                }
                "IdentifiedObject.mRID" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { obj.base.base.base.m_rid = sv.clone(); }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { obj.base.base.base.m_rid = sv.clone(); }
                        }
                        _ => {}
                    }
                }
                "IdentifiedObject.name" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { obj.base.base.base.name = sv.clone(); }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { obj.base.base.base.name = sv.clone(); }
                        }
                        _ => {}
                    }
                }
                "IdentifiedObject.shortName" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { obj.base.base.base.short_name = sv.clone(); }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { obj.base.base.base.short_name = sv.clone(); }
                        }
                        _ => {}
                    }
                }
                _ => {}
            }
        }
        obj
    }
}
