/// Detailed electro-hydraulic governor for steam unit.
#[derive(Debug, Default, Clone, serde::Serialize, serde::Deserialize)]
pub struct GovSteamFV4 {
    #[serde(flatten)]
    pub base: super::TurbineGovernorDynamics,
    /// Minimum value of pressure regulator output (Cpsmn). Typical value = -1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpsmn: Option<f64>,
    /// Maximum value of pressure regulator output (Cpsmx). Typical value = 1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpsmx: Option<f64>,
    /// Minimum value of regulator set-point (Crmn). Typical value = 0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub crmn: Option<f64>,
    /// Maximum value of regulator set-point (Crmx). Typical value = 1,2.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub crmx: Option<f64>,
    /// Derivative gain of pressure regulator (Kdc). Typical value = 1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kdc: Option<f64>,
    /// Frequency bias (reciprocal of droop) (Kf1). Typical value = 20.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kf1: Option<f64>,
    /// Frequency control (reciprocal of droop) (Kf3). Typical value = 20.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kf3: Option<f64>,
    /// Fraction of total turbine output generated by HP part (Khp). Typical value = 0,35.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub khp: Option<f64>,
    /// Integral gain of pressure regulator (Kic). Typical value = 0,0033.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kic: Option<f64>,
    /// Integral gain of pressure feedback regulator (Kip). Typical value = 0,5.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kip: Option<f64>,
    /// Integral gain of electro-hydraulic regulator (Kit). Typical value = 0,04.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kit: Option<f64>,
    /// First gain coefficient of intercept valves characteristic (Kmp1). Typical value = 0,5.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kmp1: Option<f64>,
    /// Second gain coefficient of intercept valves characteristic (Kmp2). Typical value = 3,5.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kmp2: Option<f64>,
    /// Proportional gain of pressure regulator (Kpc). Typical value = 0,5.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kpc: Option<f64>,
    /// Proportional gain of pressure feedback regulator (Kpp). Typical value = 1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kpp: Option<f64>,
    /// Proportional gain of electro-hydraulic regulator (Kpt). Typical value = 0,3.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kpt: Option<f64>,
    /// Maximum variation of fuel flow (Krc). Typical value = 0,05.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub krc: Option<f64>,
    /// Pressure loss due to flow friction in the boiler tubes (Ksh). Typical value = 0,08.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ksh: Option<f64>,
    /// Maximum negative power error (Lpi). Typical value = -0,15.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lpi: Option<f64>,
    /// Maximum positive power error (Lps). Typical value = 0,03.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lps: Option<f64>,
    /// Lower limit for frequency correction (MNEF). Typical value = -0,05.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mnef: Option<f64>,
    /// Upper limit for frequency correction (MXEF). Typical value = 0,05.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mxef: Option<f64>,
    /// First value of pressure set point static characteristic (Pr1). Typical value = 0,2.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pr1: Option<f64>,
    /// Second value of pressure set point static characteristic, corresponding to Ps0 = 1,0 PU (Pr2). Typical value = 0,75.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pr2: Option<f64>,
    /// Minimum value of pressure set point static characteristic (Psmn). Typical value = 1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub psmn: Option<f64>,
    /// Minimum value of integral regulator (Rsmimn). Typical value = 0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rsmimn: Option<f64>,
    /// Maximum value of integral regulator (Rsmimx). Typical value = 1,1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rsmimx: Option<f64>,
    /// Minimum value of integral regulator (Rvgmn). Typical value = 0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rvgmn: Option<f64>,
    /// Maximum value of integral regulator (Rvgmx). Typical value = 1,2.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rvgmx: Option<f64>,
    /// Minimum valve opening (Srmn). Typical value = 0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub srmn: Option<f64>,
    /// Maximum valve opening (Srmx). Typical value = 1,1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub srmx: Option<f64>,
    /// Intercept valves characteristic discontinuity point (Srsmp). Typical value = 0,43.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub srsmp: Option<f64>,
    /// Maximum regulator gate closing velocity (Svmn). Typical value = -0,0333.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub svmn: Option<f64>,
    /// Maximum regulator gate opening velocity (Svmx). Typical value = 0,0333.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub svmx: Option<f64>,
    /// Control valves rate opening time (Ta) (>= 0). Typical value = 0,8.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ta: Option<f64>,
    /// Intercept valves rate opening time (Tam) (>= 0). Typical value = 0,8.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tam: Option<f64>,
    /// Control valves rate closing time (Tc) (>= 0). Typical value = 0,5.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tc: Option<f64>,
    /// Intercept valves rate closing time (Tcm) (>= 0). Typical value = 0,5.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tcm: Option<f64>,
    /// Derivative time constant of pressure regulator (Tdc) (>= 0). Typical value = 90.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tdc: Option<f64>,
    /// Time constant of fuel regulation (Tf1) (>= 0). Typical value = 10.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tf1: Option<f64>,
    /// Time constant of steam chest (Tf2) (>= 0). Typical value = 10.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tf2: Option<f64>,
    /// High pressure (HP) time constant of the turbine (Thp) (>= 0). Typical value = 0,15.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thp: Option<f64>,
    /// Low pressure (LP) time constant of the turbine (Tmp) (>= 0). Typical value = 0,4.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tmp: Option<f64>,
    /// Reheater time constant of the turbine (Trh) (>= 0). Typical value = 10.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trh: Option<f64>,
    /// Boiler time constant (Tv) (>= 0). Typical value = 60.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tv: Option<f64>,
    /// Control valves servo time constant (Ty) (>= 0). Typical value = 0,1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ty: Option<f64>,
    /// Coefficient of linearized equations of turbine (Stodola formulation) (Y). Typical value = 0,13.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub y: Option<f64>,
    /// Minimum control valve position (Yhpmn). Typical value = 0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub yhpmn: Option<f64>,
    /// Maximum control valve position (Yhpmx). Typical value = 1,1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub yhpmx: Option<f64>,
    /// Minimum intercept valve position (Ympmn). Typical value = 0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ympmn: Option<f64>,
    /// Maximum intercept valve position (Ympmx). Typical value = 1,1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ympmx: Option<f64>,
}
impl crate::base::CimElement for GovSteamFV4 {
    fn mrid(&self) -> &str { &self.base.base.base.id }
    fn type_name(&self) -> &'static str { "GovSteamFV4" }
    fn as_any(&self) -> &dyn std::any::Any { self }
    fn to_json_value(&self) -> serde_json::Value {
        serde_json::to_value(self).unwrap_or(serde_json::Value::Null)
    }
    fn to_block(&self) -> crate::base::RdfBlock {
        let mut block = self.base.to_block();
        block.type_name = "GovSteamFV4".to_string();
        if let Some(v) = self.cpsmn {
            block.fields.insert("GovSteamFV4.cpsmn".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.cpsmx {
            block.fields.insert("GovSteamFV4.cpsmx".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.crmn {
            block.fields.insert("GovSteamFV4.crmn".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.crmx {
            block.fields.insert("GovSteamFV4.crmx".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.kdc {
            block.fields.insert("GovSteamFV4.kdc".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.kf1 {
            block.fields.insert("GovSteamFV4.kf1".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.kf3 {
            block.fields.insert("GovSteamFV4.kf3".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.khp {
            block.fields.insert("GovSteamFV4.khp".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.kic {
            block.fields.insert("GovSteamFV4.kic".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.kip {
            block.fields.insert("GovSteamFV4.kip".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.kit {
            block.fields.insert("GovSteamFV4.kit".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.kmp1 {
            block.fields.insert("GovSteamFV4.kmp1".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.kmp2 {
            block.fields.insert("GovSteamFV4.kmp2".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.kpc {
            block.fields.insert("GovSteamFV4.kpc".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.kpp {
            block.fields.insert("GovSteamFV4.kpp".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.kpt {
            block.fields.insert("GovSteamFV4.kpt".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.krc {
            block.fields.insert("GovSteamFV4.krc".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.ksh {
            block.fields.insert("GovSteamFV4.ksh".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.lpi {
            block.fields.insert("GovSteamFV4.lpi".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.lps {
            block.fields.insert("GovSteamFV4.lps".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.mnef {
            block.fields.insert("GovSteamFV4.mnef".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.mxef {
            block.fields.insert("GovSteamFV4.mxef".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.pr1 {
            block.fields.insert("GovSteamFV4.pr1".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.pr2 {
            block.fields.insert("GovSteamFV4.pr2".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.psmn {
            block.fields.insert("GovSteamFV4.psmn".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.rsmimn {
            block.fields.insert("GovSteamFV4.rsmimn".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.rsmimx {
            block.fields.insert("GovSteamFV4.rsmimx".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.rvgmn {
            block.fields.insert("GovSteamFV4.rvgmn".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.rvgmx {
            block.fields.insert("GovSteamFV4.rvgmx".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.srmn {
            block.fields.insert("GovSteamFV4.srmn".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.srmx {
            block.fields.insert("GovSteamFV4.srmx".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.srsmp {
            block.fields.insert("GovSteamFV4.srsmp".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.svmn {
            block.fields.insert("GovSteamFV4.svmn".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.svmx {
            block.fields.insert("GovSteamFV4.svmx".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.ta {
            block.fields.insert("GovSteamFV4.ta".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tam {
            block.fields.insert("GovSteamFV4.tam".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tc {
            block.fields.insert("GovSteamFV4.tc".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tcm {
            block.fields.insert("GovSteamFV4.tcm".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tdc {
            block.fields.insert("GovSteamFV4.tdc".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tf1 {
            block.fields.insert("GovSteamFV4.tf1".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tf2 {
            block.fields.insert("GovSteamFV4.tf2".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.thp {
            block.fields.insert("GovSteamFV4.thp".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tmp {
            block.fields.insert("GovSteamFV4.tmp".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.trh {
            block.fields.insert("GovSteamFV4.trh".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.tv {
            block.fields.insert("GovSteamFV4.tv".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.ty {
            block.fields.insert("GovSteamFV4.ty".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.y {
            block.fields.insert("GovSteamFV4.y".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.yhpmn {
            block.fields.insert("GovSteamFV4.yhpmn".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.yhpmx {
            block.fields.insert("GovSteamFV4.yhpmx".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.ympmn {
            block.fields.insert("GovSteamFV4.ympmn".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        if let Some(v) = self.ympmx {
            block.fields.insert("GovSteamFV4.ympmx".into(), crate::base::FieldValue::Text(v.to_string()));
        }
        block
    }
}

impl GovSteamFV4 {
    pub fn from_block(b: &crate::base::RdfBlock) -> Self {
        let mut obj = Self::default();
        obj.base.base.base.id.clone_from(&b.mrid);
        for (key, val) in &b.fields {
            match key.as_str() {
                "GovSteamFV4.cpsmn" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.cpsmn = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.cpsmn = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.cpsmx" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.cpsmx = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.cpsmx = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.crmn" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.crmn = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.crmn = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.crmx" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.crmx = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.crmx = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.kdc" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.kdc = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.kdc = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.kf1" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.kf1 = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.kf1 = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.kf3" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.kf3 = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.kf3 = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.khp" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.khp = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.khp = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.kic" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.kic = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.kic = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.kip" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.kip = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.kip = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.kit" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.kit = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.kit = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.kmp1" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.kmp1 = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.kmp1 = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.kmp2" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.kmp2 = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.kmp2 = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.kpc" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.kpc = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.kpc = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.kpp" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.kpp = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.kpp = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.kpt" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.kpt = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.kpt = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.krc" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.krc = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.krc = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.ksh" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.ksh = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.ksh = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.lpi" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.lpi = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.lpi = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.lps" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.lps = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.lps = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.mnef" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.mnef = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.mnef = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.mxef" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.mxef = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.mxef = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.pr1" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.pr1 = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.pr1 = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.pr2" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.pr2 = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.pr2 = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.psmn" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.psmn = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.psmn = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.rsmimn" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.rsmimn = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.rsmimn = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.rsmimx" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.rsmimx = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.rsmimx = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.rvgmn" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.rvgmn = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.rvgmn = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.rvgmx" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.rvgmx = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.rvgmx = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.srmn" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.srmn = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.srmn = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.srmx" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.srmx = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.srmx = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.srsmp" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.srsmp = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.srsmp = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.svmn" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.svmn = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.svmn = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.svmx" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.svmx = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.svmx = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.ta" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.ta = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.ta = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.tam" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tam = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tam = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.tc" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tc = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tc = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.tcm" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tcm = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tcm = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.tdc" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tdc = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tdc = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.tf1" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tf1 = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tf1 = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.tf2" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tf2 = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tf2 = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.thp" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.thp = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.thp = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.tmp" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tmp = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tmp = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.trh" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.trh = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.trh = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.tv" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.tv = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.tv = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.ty" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.ty = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.ty = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.y" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.y = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.y = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.yhpmn" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.yhpmn = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.yhpmn = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.yhpmx" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.yhpmx = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.yhpmx = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.ympmn" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.ympmn = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.ympmn = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "GovSteamFV4.ympmx" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { if let Ok(v) = sv.trim().parse() { obj.ympmx = Some(v); } }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { if let Ok(v) = sv.trim().parse() { obj.ympmx = Some(v); } }
                        }
                        _ => {}
                    }
                }
                "TurbineGovernorDynamics.AsynchronousMachineDynamics" => {
                    if let crate::base::FieldValue::Resource(sv) = val {
                        obj.base.asynchronous_machine_dynamics = Some(crate::base::MridRef { mrid: sv.clone() });
                    }
                }
                "TurbineGovernorDynamics.SynchronousMachineDynamics" => {
                    if let crate::base::FieldValue::Resource(sv) = val {
                        obj.base.synchronous_machine_dynamics = Some(crate::base::MridRef { mrid: sv.clone() });
                    }
                }
                "DynamicsFunctionBlock.enabled" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { obj.base.base.enabled = Some(sv.trim() == "true"); }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { obj.base.base.enabled = Some(sv.trim() == "true"); }
                        }
                        _ => {}
                    }
                }
                "IdentifiedObject.description" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { obj.base.base.base.description = sv.clone(); }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { obj.base.base.base.description = sv.clone(); }
                        }
                        _ => {}
                    }
                }
                "IdentifiedObject.energyIdentCodeEic" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { obj.base.base.base.energy_ident_code_eic = sv.clone(); }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { obj.base.base.base.energy_ident_code_eic = sv.clone(); }
                        }
                        _ => {}
                    }
                }
                "IdentifiedObject.mRID" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { obj.base.base.base.m_rid = sv.clone(); }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { obj.base.base.base.m_rid = sv.clone(); }
                        }
                        _ => {}
                    }
                }
                "IdentifiedObject.name" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { obj.base.base.base.name = sv.clone(); }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { obj.base.base.base.name = sv.clone(); }
                        }
                        _ => {}
                    }
                }
                "IdentifiedObject.shortName" => {
                    match val {
                        crate::base::FieldValue::Text(sv) => { obj.base.base.base.short_name = sv.clone(); }
                        crate::base::FieldValue::TextList(svs) => {
                            if let Some(sv) = svs.last() { obj.base.base.base.short_name = sv.clone(); }
                        }
                        _ => {}
                    }
                }
                _ => {}
            }
        }
        obj
    }
}
