// Generated by cimgen — do not edit by hand.
#![allow(clippy::all, dead_code, unused)]
use cimdecoder::CimDataset;
use crate::Violation;
use crate::helpers::*;

pub fn validate_p61970_301_operation_ap_con_complex_shacl(dataset: &CimDataset) -> Vec<Violation> {
    let mut v = Vec::new();
    v.extend(check_p61970_301_operation_ap_con_complex_shacl_accumulator_limit_accumulator_limit_value_min_excl(dataset));
    v
}

pub fn check_p61970_301_operation_ap_con_complex_shacl_accumulator_limit_accumulator_limit_value_min_excl(dataset: &CimDataset) -> Vec<Violation> {
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("AccumulatorLimit").into_iter().flatten() {
        let entry = &dataset.entries[mrid];
        let obj = match entry.element.as_any()
            .downcast_ref::<cimstructs::AccumulatorLimit>() {
            Some(o) => o, None => continue,
        };
        if obj.value.is_none() { continue; }
        if (obj.value.unwrap() as f64) <= 0_f64 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "opu:AccumulatorLimit.value-valueRange".to_string(),
                class:       "AccumulatorLimit".to_string(),
                property:    "AccumulatorLimit.value".to_string(),
                message:     "The value is negative or zero.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "C:301:OP:AccumulatorLimit.value:valueRange".to_string(),
                description: "The value is positive.".to_string(),
            });
        }
    }
    violations
}

