// Generated by cimgen — do not edit by hand.
#![allow(clippy::all, dead_code, unused)]
use cimdecoder::CimDataset;
use crate::Violation;
use crate::helpers::*;

pub fn validate_p61970_600_2_equipmentboundary_ap_con_complex_inverseassociation_shacl(dataset: &CimDataset) -> Vec<Violation> {
    let mut v = Vec::new();
    v.extend(check_p61970_600_2_equipmentboundary_ap_con_complex_inverseassociation_shacl_connectivity_node_bo_etc(dataset));
    v
}

pub fn check_p61970_600_2_equipmentboundary_ap_con_complex_inverseassociation_shacl_connectivity_node_bo_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("BoundaryPoint").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::BoundaryPoint>()) {
            if let Some(r) = &src.connectivity_node { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("ConnectivityNode").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqbdi:ConnectivityNode.BoundaryPoint-cardinality".to_string(),
                class:       "ConnectivityNode".to_string(),
                property:    "ConnectivityNode.BoundaryPoint-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "ConnectivityNode.BoundaryPoint-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

