// Generated by cimgen — do not edit by hand.
#![allow(clippy::all, dead_code, unused)]
use cimdecoder::CimDataset;
use crate::Violation;
use crate::helpers::*;

pub fn validate_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl(dataset: &CimDataset) -> Vec<Violation> {
    let mut v = Vec::new();
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_bus_name_marker_acdc_termina_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_caes_plant_thermal_generatin_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_conform_load_group_conform_l_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_connectivity_node_boundary_p_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_gross_to_net_active_power_cu_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_reactive_capability_curve_cu_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_vs_capability_curve_curve_da_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_sub_load_area_control_area_e_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_load_area_control_area_energ_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_generating_unit_rotating_mac_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_hydro_generating_unit_rotati_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_nuclear_generating_unit_rota_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_solar_generating_unit_rotati_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_thermal_generating_unit_rota_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_wind_generating_unit_rotatin_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_load_area_sub_load_area_load_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_non_conform_load_group_non_c_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_nonlinear_shunt_compensator_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_phase_tap_changer_table_phas_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_power_electronics_wind_unit_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_photo_voltaic_unit_power_ele_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_battery_unit_power_electroni_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_ratio_tap_changer_table_rati_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_reactive_capability_curve_sy_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_conform_load_schedule_regula_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_non_conform_load_schedule_re_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_regulation_schedule_regular_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_switch_schedule_regular_time_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_tap_schedule_regular_time_po_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_synchronous_machine_hydro_pu_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_asynchronous_machine_hydro_p_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_sub_load_area_load_group_sub_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_tap_changer_control_tap_chan_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_terminal_tie_flow_terminal_m_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_power_transformer_end_phase_etc(dataset));
    v.extend(check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_power_transformer_end_ratio_etc(dataset));
    v
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_bus_name_marker_acdc_termina_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("ACDCConverterDCTerminal").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::ACDCConverterDCTerminal>()) {
            if let Some(r) = &src.base.base.bus_name_marker { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("ACDCTerminal").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::ACDCTerminal>()) {
            if let Some(r) = &src.bus_name_marker { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("DCBaseTerminal").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::DCBaseTerminal>()) {
            if let Some(r) = &src.base.bus_name_marker { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("DCTerminal").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::DCTerminal>()) {
            if let Some(r) = &src.base.base.bus_name_marker { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("Terminal").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::Terminal>()) {
            if let Some(r) = &src.base.bus_name_marker { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("BusNameMarker").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:BusNameMarker.Terminal-cardinality".to_string(),
                class:       "BusNameMarker".to_string(),
                property:    "BusNameMarker.Terminal-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "BusNameMarker.Terminal-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_caes_plant_thermal_generatin_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("ThermalGeneratingUnit").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::ThermalGeneratingUnit>()) {
            if let Some(r) = &src.caes_plant { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("CAESPlant").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:CAESPlant.ThermalGeneratingUnit-cardinality".to_string(),
                class:       "CAESPlant".to_string(),
                property:    "CAESPlant.ThermalGeneratingUnit-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "CAESPlant.ThermalGeneratingUnit-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_conform_load_group_conform_l_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("ConformLoad").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::ConformLoad>()) {
            if let Some(r) = &src.load_group { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("ConformLoadGroup").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:ConformLoadGroup.EnergyConsumers-cardinality".to_string(),
                class:       "ConformLoadGroup".to_string(),
                property:    "ConformLoadGroup.EnergyConsumers-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "ConformLoadGroup.EnergyConsumers-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_connectivity_node_boundary_p_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("BoundaryPoint").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::BoundaryPoint>()) {
            if let Some(r) = &src.connectivity_node { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("ConnectivityNode").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:ConnectivityNode.BoundaryPoint-cardinality".to_string(),
                class:       "ConnectivityNode".to_string(),
                property:    "ConnectivityNode.BoundaryPoint-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "ConnectivityNode.BoundaryPoint-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_gross_to_net_active_power_cu_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("CurveData").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::CurveData>()) {
            if let Some(r) = &src.curve { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("GrossToNetActivePowerCurve").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:Curve.CurveDatas-cardinality".to_string(),
                class:       "GrossToNetActivePowerCurve".to_string(),
                property:    "Curve.CurveDatas-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "Curve.CurveDatas-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_reactive_capability_curve_cu_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("CurveData").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::CurveData>()) {
            if let Some(r) = &src.curve { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("ReactiveCapabilityCurve").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:Curve.CurveDatas-cardinality".to_string(),
                class:       "ReactiveCapabilityCurve".to_string(),
                property:    "Curve.CurveDatas-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "Curve.CurveDatas-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_vs_capability_curve_curve_da_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("CurveData").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::CurveData>()) {
            if let Some(r) = &src.curve { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("VsCapabilityCurve").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:Curve.CurveDatas-cardinality".to_string(),
                class:       "VsCapabilityCurve".to_string(),
                property:    "Curve.CurveDatas-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "Curve.CurveDatas-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_sub_load_area_control_area_e_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("ControlArea").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::ControlArea>()) {
            if let Some(r) = &src.energy_area { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("SubLoadArea").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:EnergyArea.ControlArea-cardinality".to_string(),
                class:       "SubLoadArea".to_string(),
                property:    "EnergyArea.ControlArea-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "EnergyArea.ControlArea-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_load_area_control_area_energ_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("ControlArea").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::ControlArea>()) {
            if let Some(r) = &src.energy_area { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("LoadArea").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:EnergyArea.ControlArea-cardinality".to_string(),
                class:       "LoadArea".to_string(),
                property:    "EnergyArea.ControlArea-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "EnergyArea.ControlArea-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_generating_unit_rotating_mac_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("AsynchronousMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::AsynchronousMachine>()) {
            if let Some(r) = &src.base.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("RotatingMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RotatingMachine>()) {
            if let Some(r) = &src.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("SynchronousMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::SynchronousMachine>()) {
            if let Some(r) = &src.base.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("GeneratingUnit").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:GeneratingUnit.RotatingMachine-cardinality".to_string(),
                class:       "GeneratingUnit".to_string(),
                property:    "GeneratingUnit.RotatingMachine-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "GeneratingUnit.RotatingMachine-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_hydro_generating_unit_rotati_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("AsynchronousMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::AsynchronousMachine>()) {
            if let Some(r) = &src.base.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("RotatingMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RotatingMachine>()) {
            if let Some(r) = &src.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("SynchronousMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::SynchronousMachine>()) {
            if let Some(r) = &src.base.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("HydroGeneratingUnit").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:GeneratingUnit.RotatingMachine-cardinality".to_string(),
                class:       "HydroGeneratingUnit".to_string(),
                property:    "GeneratingUnit.RotatingMachine-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "GeneratingUnit.RotatingMachine-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_nuclear_generating_unit_rota_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("AsynchronousMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::AsynchronousMachine>()) {
            if let Some(r) = &src.base.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("RotatingMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RotatingMachine>()) {
            if let Some(r) = &src.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("SynchronousMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::SynchronousMachine>()) {
            if let Some(r) = &src.base.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("NuclearGeneratingUnit").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:GeneratingUnit.RotatingMachine-cardinality".to_string(),
                class:       "NuclearGeneratingUnit".to_string(),
                property:    "GeneratingUnit.RotatingMachine-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "GeneratingUnit.RotatingMachine-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_solar_generating_unit_rotati_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("AsynchronousMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::AsynchronousMachine>()) {
            if let Some(r) = &src.base.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("RotatingMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RotatingMachine>()) {
            if let Some(r) = &src.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("SynchronousMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::SynchronousMachine>()) {
            if let Some(r) = &src.base.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("SolarGeneratingUnit").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:GeneratingUnit.RotatingMachine-cardinality".to_string(),
                class:       "SolarGeneratingUnit".to_string(),
                property:    "GeneratingUnit.RotatingMachine-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "GeneratingUnit.RotatingMachine-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_thermal_generating_unit_rota_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("AsynchronousMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::AsynchronousMachine>()) {
            if let Some(r) = &src.base.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("RotatingMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RotatingMachine>()) {
            if let Some(r) = &src.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("SynchronousMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::SynchronousMachine>()) {
            if let Some(r) = &src.base.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("ThermalGeneratingUnit").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:GeneratingUnit.RotatingMachine-cardinality".to_string(),
                class:       "ThermalGeneratingUnit".to_string(),
                property:    "GeneratingUnit.RotatingMachine-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "GeneratingUnit.RotatingMachine-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_wind_generating_unit_rotatin_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("AsynchronousMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::AsynchronousMachine>()) {
            if let Some(r) = &src.base.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("RotatingMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RotatingMachine>()) {
            if let Some(r) = &src.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("SynchronousMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::SynchronousMachine>()) {
            if let Some(r) = &src.base.generating_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("WindGeneratingUnit").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:GeneratingUnit.RotatingMachine-cardinality".to_string(),
                class:       "WindGeneratingUnit".to_string(),
                property:    "GeneratingUnit.RotatingMachine-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "GeneratingUnit.RotatingMachine-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_load_area_sub_load_area_load_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("SubLoadArea").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::SubLoadArea>()) {
            if let Some(r) = &src.load_area { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("LoadArea").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:LoadArea.SubLoadAreas-cardinality".to_string(),
                class:       "LoadArea".to_string(),
                property:    "LoadArea.SubLoadAreas-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "LoadArea.SubLoadAreas-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_non_conform_load_group_non_c_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("NonConformLoad").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::NonConformLoad>()) {
            if let Some(r) = &src.load_group { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("NonConformLoadGroup").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:NonConformLoadGroup.EnergyConsumers-cardinality".to_string(),
                class:       "NonConformLoadGroup".to_string(),
                property:    "NonConformLoadGroup.EnergyConsumers-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "NonConformLoadGroup.EnergyConsumers-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_nonlinear_shunt_compensator_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("NonlinearShuntCompensatorPoint").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::NonlinearShuntCompensatorPoint>()) {
            if let Some(r) = &src.nonlinear_shunt_compensator { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("NonlinearShuntCompensator").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:NonlinearShuntCompensator.NonlinearShuntCompensatorPoints-cardinality".to_string(),
                class:       "NonlinearShuntCompensator".to_string(),
                property:    "NonlinearShuntCompensator.NonlinearShuntCompensatorPoints-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "NonlinearShuntCompensator.NonlinearShuntCompensatorPoints-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_phase_tap_changer_table_phas_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("PhaseTapChangerTablePoint").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PhaseTapChangerTablePoint>()) {
            if let Some(r) = &src.phase_tap_changer_table { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("PhaseTapChangerTable").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:PhaseTapChangerTable.PhaseTapChangerTablePoint-cardinality".to_string(),
                class:       "PhaseTapChangerTable".to_string(),
                property:    "PhaseTapChangerTable.PhaseTapChangerTablePoint-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "PhaseTapChangerTable.PhaseTapChangerTablePoint-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_power_electronics_wind_unit_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("PowerElectronicsConnection").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PowerElectronicsConnection>()) {
            if let Some(r) = &src.power_electronics_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("PowerElectronicsWindUnit").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:PowerElectronicsUnit.PowerElectronicsConnection-cardinality".to_string(),
                class:       "PowerElectronicsWindUnit".to_string(),
                property:    "PowerElectronicsUnit.PowerElectronicsConnection-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "PowerElectronicsUnit.PowerElectronicsConnection-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_photo_voltaic_unit_power_ele_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("PowerElectronicsConnection").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PowerElectronicsConnection>()) {
            if let Some(r) = &src.power_electronics_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("PhotoVoltaicUnit").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:PowerElectronicsUnit.PowerElectronicsConnection-cardinality".to_string(),
                class:       "PhotoVoltaicUnit".to_string(),
                property:    "PowerElectronicsUnit.PowerElectronicsConnection-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "PowerElectronicsUnit.PowerElectronicsConnection-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_battery_unit_power_electroni_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("PowerElectronicsConnection").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PowerElectronicsConnection>()) {
            if let Some(r) = &src.power_electronics_unit { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("BatteryUnit").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:PowerElectronicsUnit.PowerElectronicsConnection-cardinality".to_string(),
                class:       "BatteryUnit".to_string(),
                property:    "PowerElectronicsUnit.PowerElectronicsConnection-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "PowerElectronicsUnit.PowerElectronicsConnection-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_ratio_tap_changer_table_rati_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("RatioTapChangerTablePoint").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RatioTapChangerTablePoint>()) {
            if let Some(r) = &src.ratio_tap_changer_table { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("RatioTapChangerTable").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:RatioTapChangerTable.RatioTapChangerTablePoint-cardinality".to_string(),
                class:       "RatioTapChangerTable".to_string(),
                property:    "RatioTapChangerTable.RatioTapChangerTablePoint-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "RatioTapChangerTable.RatioTapChangerTablePoint-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_reactive_capability_curve_sy_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("SynchronousMachine").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::SynchronousMachine>()) {
            if let Some(r) = &src.initial_reactive_capability_curve { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("ReactiveCapabilityCurve").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:ReactiveCapabilityCurve.InitiallyUsedBySynchronousMachines-cardinality".to_string(),
                class:       "ReactiveCapabilityCurve".to_string(),
                property:    "ReactiveCapabilityCurve.InitiallyUsedBySynchronousMachines-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "ReactiveCapabilityCurve.InitiallyUsedBySynchronousMachines-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_conform_load_schedule_regula_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("RegularTimePoint").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RegularTimePoint>()) {
            if let Some(r) = &src.interval_schedule { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("ConformLoadSchedule").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                class:       "ConformLoadSchedule".to_string(),
                property:    "RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_non_conform_load_schedule_re_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("RegularTimePoint").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RegularTimePoint>()) {
            if let Some(r) = &src.interval_schedule { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("NonConformLoadSchedule").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                class:       "NonConformLoadSchedule".to_string(),
                property:    "RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_regulation_schedule_regular_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("RegularTimePoint").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RegularTimePoint>()) {
            if let Some(r) = &src.interval_schedule { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("RegulationSchedule").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                class:       "RegulationSchedule".to_string(),
                property:    "RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_switch_schedule_regular_time_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("RegularTimePoint").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RegularTimePoint>()) {
            if let Some(r) = &src.interval_schedule { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("SwitchSchedule").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                class:       "SwitchSchedule".to_string(),
                property:    "RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_tap_schedule_regular_time_po_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("RegularTimePoint").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RegularTimePoint>()) {
            if let Some(r) = &src.interval_schedule { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("TapSchedule").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                class:       "TapSchedule".to_string(),
                property:    "RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "RegularIntervalSchedule.TimePoints-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_synchronous_machine_hydro_pu_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("HydroPump").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::HydroPump>()) {
            if let Some(r) = &src.rotating_machine { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("SynchronousMachine").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:RotatingMachine.HydroPump-cardinality".to_string(),
                class:       "SynchronousMachine".to_string(),
                property:    "RotatingMachine.HydroPump-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "RotatingMachine.HydroPump-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_asynchronous_machine_hydro_p_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("HydroPump").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::HydroPump>()) {
            if let Some(r) = &src.rotating_machine { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("AsynchronousMachine").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:RotatingMachine.HydroPump-cardinality".to_string(),
                class:       "AsynchronousMachine".to_string(),
                property:    "RotatingMachine.HydroPump-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "RotatingMachine.HydroPump-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_sub_load_area_load_group_sub_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("ConformLoadGroup").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::ConformLoadGroup>()) {
            if let Some(r) = &src.base.sub_load_area { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("LoadGroup").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::LoadGroup>()) {
            if let Some(r) = &src.sub_load_area { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("NonConformLoadGroup").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::NonConformLoadGroup>()) {
            if let Some(r) = &src.base.sub_load_area { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("SubLoadArea").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:SubLoadArea.LoadGroups-cardinality".to_string(),
                class:       "SubLoadArea".to_string(),
                property:    "SubLoadArea.LoadGroups-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "SubLoadArea.LoadGroups-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_tap_changer_control_tap_chan_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("PhaseTapChanger").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PhaseTapChanger>()) {
            if let Some(r) = &src.base.tap_changer_control { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("PhaseTapChangerAsymmetrical").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PhaseTapChangerAsymmetrical>()) {
            if let Some(r) = &src.base.base.base.tap_changer_control { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("PhaseTapChangerLinear").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PhaseTapChangerLinear>()) {
            if let Some(r) = &src.base.base.tap_changer_control { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("PhaseTapChangerNonLinear").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PhaseTapChangerNonLinear>()) {
            if let Some(r) = &src.base.base.tap_changer_control { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("PhaseTapChangerSymmetrical").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PhaseTapChangerSymmetrical>()) {
            if let Some(r) = &src.base.base.base.tap_changer_control { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("PhaseTapChangerTabular").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PhaseTapChangerTabular>()) {
            if let Some(r) = &src.base.base.tap_changer_control { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("RatioTapChanger").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RatioTapChanger>()) {
            if let Some(r) = &src.base.tap_changer_control { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("TapChanger").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::TapChanger>()) {
            if let Some(r) = &src.tap_changer_control { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("TapChangerControl").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:TapChangerControl.TapChanger-cardinality".to_string(),
                class:       "TapChangerControl".to_string(),
                property:    "TapChangerControl.TapChanger-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "TapChangerControl.TapChanger-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_terminal_tie_flow_terminal_m_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("TieFlow").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::TieFlow>()) {
            if let Some(r) = &src.terminal { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("Terminal").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 2 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:Terminal.TieFlow-cardinality".to_string(),
                class:       "Terminal".to_string(),
                property:    "Terminal.TieFlow-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "Terminal.TieFlow-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_power_transformer_end_phase_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("PhaseTapChanger").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PhaseTapChanger>()) {
            if let Some(r) = &src.transformer_end { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("PhaseTapChangerAsymmetrical").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PhaseTapChangerAsymmetrical>()) {
            if let Some(r) = &src.base.base.transformer_end { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("PhaseTapChangerLinear").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PhaseTapChangerLinear>()) {
            if let Some(r) = &src.base.transformer_end { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("PhaseTapChangerNonLinear").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PhaseTapChangerNonLinear>()) {
            if let Some(r) = &src.base.transformer_end { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("PhaseTapChangerSymmetrical").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PhaseTapChangerSymmetrical>()) {
            if let Some(r) = &src.base.base.transformer_end { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("PhaseTapChangerTabular").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::PhaseTapChangerTabular>()) {
            if let Some(r) = &src.base.transformer_end { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("PowerTransformerEnd").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:TransformerEnd.PhaseTapChanger-cardinality".to_string(),
                class:       "PowerTransformerEnd".to_string(),
                property:    "TransformerEnd.PhaseTapChanger-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "TransformerEnd.PhaseTapChanger-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_equipment_ap_con_complex_inverseassociation_shacl_power_transformer_end_ratio_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("RatioTapChanger").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RatioTapChanger>()) {
            if let Some(r) = &src.transformer_end { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("PowerTransformerEnd").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "eqi:TransformerEnd.RatioTapChanger-cardinality".to_string(),
                class:       "PowerTransformerEnd".to_string(),
                property:    "TransformerEnd.RatioTapChanger-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "TransformerEnd.RatioTapChanger-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

