// Generated by cimgen — do not edit by hand.
#![allow(clippy::all, dead_code, unused)]
use cimdecoder::CimDataset;
use crate::Violation;
use crate::helpers::*;

pub fn validate_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl(dataset: &CimDataset) -> Vec<Violation> {
    let mut v = Vec::new();
    v.extend(check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_accumulator_limit_set_accumu_etc(dataset));
    v.extend(check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_accumulator_value_accumulato_etc(dataset));
    v.extend(check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_analog_value_analog_control_etc(dataset));
    v.extend(check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_discrete_value_command_discr_etc(dataset));
    v.extend(check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_accumulator_value_measuremen_etc(dataset));
    v.extend(check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_analog_value_measurement_val_etc(dataset));
    v.extend(check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_discrete_value_measurement_v_etc(dataset));
    v.extend(check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_string_measurement_value_mea_etc(dataset));
    v.extend(check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_value_alias_set_value_to_ali_etc(dataset));
    v
}

pub fn check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_accumulator_limit_set_accumu_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("AccumulatorLimit").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::AccumulatorLimit>()) {
            if let Some(r) = &src.limit_set { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("AccumulatorLimitSet").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "opi:AccumulatorLimitSet.Limits-cardinality".to_string(),
                class:       "AccumulatorLimitSet".to_string(),
                property:    "AccumulatorLimitSet.Limits-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "AccumulatorLimitSet.Limits-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_accumulator_value_accumulato_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("AccumulatorReset").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::AccumulatorReset>()) {
            if let Some(r) = &src.accumulator_value { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("AccumulatorValue").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "opi:AccumulatorValue.AccumulatorReset-cardinality".to_string(),
                class:       "AccumulatorValue".to_string(),
                property:    "AccumulatorValue.AccumulatorReset-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "AccumulatorValue.AccumulatorReset-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_analog_value_analog_control_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("AnalogControl").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::AnalogControl>()) {
            if let Some(r) = &src.analog_value { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("RaiseLowerCommand").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::RaiseLowerCommand>()) {
            if let Some(r) = &src.base.analog_value { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    for src_mrid in dataset.by_type.get("SetPoint").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::SetPoint>()) {
            if let Some(r) = &src.base.analog_value { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("AnalogValue").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "opi:AnalogValue.AnalogControl-cardinality".to_string(),
                class:       "AnalogValue".to_string(),
                property:    "AnalogValue.AnalogControl-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "AnalogValue.AnalogControl-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_discrete_value_command_discr_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("Command").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::Command>()) {
            if let Some(r) = &src.discrete_value { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("DiscreteValue").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "opi:DiscreteValue.Command-cardinality".to_string(),
                class:       "DiscreteValue".to_string(),
                property:    "DiscreteValue.Command-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "DiscreteValue.Command-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_accumulator_value_measuremen_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("MeasurementValueQuality").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::MeasurementValueQuality>()) {
            if let Some(r) = &src.measurement_value { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("AccumulatorValue").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "opi:MeasurementValue.MeasurementValueQuality-cardinality".to_string(),
                class:       "AccumulatorValue".to_string(),
                property:    "MeasurementValue.MeasurementValueQuality-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "MeasurementValue.MeasurementValueQuality-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_analog_value_measurement_val_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("MeasurementValueQuality").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::MeasurementValueQuality>()) {
            if let Some(r) = &src.measurement_value { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("AnalogValue").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "opi:MeasurementValue.MeasurementValueQuality-cardinality".to_string(),
                class:       "AnalogValue".to_string(),
                property:    "MeasurementValue.MeasurementValueQuality-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "MeasurementValue.MeasurementValueQuality-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_discrete_value_measurement_v_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("MeasurementValueQuality").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::MeasurementValueQuality>()) {
            if let Some(r) = &src.measurement_value { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("DiscreteValue").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "opi:MeasurementValue.MeasurementValueQuality-cardinality".to_string(),
                class:       "DiscreteValue".to_string(),
                property:    "MeasurementValue.MeasurementValueQuality-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "MeasurementValue.MeasurementValueQuality-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_string_measurement_value_mea_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("MeasurementValueQuality").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::MeasurementValueQuality>()) {
            if let Some(r) = &src.measurement_value { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("StringMeasurementValue").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count > 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "opi:MeasurementValue.MeasurementValueQuality-cardinality".to_string(),
                class:       "StringMeasurementValue".to_string(),
                property:    "MeasurementValue.MeasurementValueQuality-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "MeasurementValue.MeasurementValueQuality-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

pub fn check_p61970_600_2_operation_ap_con_complex_inverseassociation_shacl_value_alias_set_value_to_ali_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for src_mrid in dataset.by_type.get("ValueToAlias").into_iter().flatten() {
        if let Some(src) = dataset.entries.get(src_mrid)
            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::ValueToAlias>()) {
            if let Some(r) = &src.value_alias_set { *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }
        }
    }
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("ValueAliasSet").into_iter().flatten() {
        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);
        if count < 1 {
            violations.push(Violation {
                object_id:   mrid.clone(),
                rule_id:     "opi:ValueAliasSet.Values-cardinality".to_string(),
                class:       "ValueAliasSet".to_string(),
                property:    "ValueAliasSet.Values-cardinality".to_string(),
                message:     "Wrong number of associated instances.".to_string(),
                severity:    "sh:Violation".to_string(),
                name:        "ValueAliasSet.Values-cardinality".to_string(),
                description: "This constraint validates the cardinality of the association at the inverse direction.".to_string(),
            });
        }
    }
    violations
}

