// Generated by cimgen — do not edit by hand.
#![allow(clippy::all, dead_code, unused)]
use cimdecoder::CimDataset;
use crate::Violation;
use crate::helpers::*;

pub fn validate_p61970_600_2_operation_ap_con_complex_implicit_crossprofile_shacl(dataset: &CimDataset) -> Vec<Violation> {
    let mut v = Vec::new();
    v.extend(check_p61970_600_2_operation_ap_con_complex_implicit_crossprofile_shacl_control_control_power_sys_etc(dataset));
    v.extend(check_p61970_600_2_operation_ap_con_complex_implicit_crossprofile_shacl_measurement_measurement_t_etc(dataset));
    v.extend(check_p61970_600_2_operation_ap_con_complex_implicit_crossprofile_shacl_measurement_measurement_p_etc(dataset));
    v
}

pub fn check_p61970_600_2_operation_ap_con_complex_implicit_crossprofile_shacl_control_control_power_sys_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("Control").into_iter().flatten() {
        let entry = &dataset.entries[mrid];
        let obj = match entry.element.as_any()
            .downcast_ref::<cimstructs::Control>() {
            Some(o) => o, None => continue,
        };
        let ref_mrid = match obj.power_system_resource.as_ref() {
            Some(r) => r.mrid.trim_start_matches('#'), None => continue,
        };
        if let Some(ref_entry) = dataset.entries.get(ref_mrid) {
            let allowed: &[&str] = &["ACDCConverter", "ACLineSegment", "AsynchronousMachine", "AuxiliaryEquipment", "BatteryUnit", "Bay", "BoundaryPoint", "Breaker", "BusbarSection", "CAESPlant", "Clamp", "CogenerationPlant", "CombinedCyclePlant", "ConductingEquipment", "Conductor", "ConformLoad", "ConnectivityNodeContainer", "Connector", "ControlArea", "CsConverter", "CurrentTransformer", "Cut", "DCBreaker", "DCBusbar", "DCChopper", "DCConductingEquipment", "DCConverterUnit", "DCDisconnector", "DCEquipmentContainer", "DCGround", "DCLine", "DCLineSegment", "DCSeriesDevice", "DCShunt", "DCSwitch", "DisconnectingCircuitBreaker", "Disconnector", "EarthFaultCompensator", "EnergyConnection", "EnergyConsumer", "EnergySource", "Equipment", "EquipmentContainer", "EquivalentBranch", "EquivalentEquipment", "EquivalentInjection", "EquivalentNetwork", "EquivalentShunt", "ExternalNetworkInjection", "FaultIndicator", "Fuse", "GeneratingUnit", "Ground", "GroundDisconnector", "GroundingImpedance", "HydroGeneratingUnit", "HydroPowerPlant", "HydroPump", "Jumper", "Junction", "Line", "LinearShuntCompensator", "LoadBreakSwitch", "NonConformLoad", "NonlinearShuntCompensator", "NuclearGeneratingUnit", "PetersenCoil", "PhaseTapChanger", "PhaseTapChangerAsymmetrical", "PhaseTapChangerLinear", "PhaseTapChangerNonLinear", "PhaseTapChangerSymmetrical", "PhaseTapChangerTabular", "PhotoVoltaicUnit", "PostLineSensor", "PotentialTransformer", "PowerElectronicsConnection", "PowerElectronicsUnit", "PowerElectronicsWindUnit", "PowerSystemResource", "PowerTransformer", "ProtectedSwitch", "RatioTapChanger", "RegulatingCondEq", "RegulatingControl", "RotatingMachine", "Sensor", "SeriesCompensator", "ShuntCompensator", "SolarGeneratingUnit", "SolarPowerPlant", "StaticVarCompensator", "StationSupply", "Substation", "SurgeArrester", "Switch", "SynchronousMachine", "TapChanger", "TapChangerControl", "ThermalGeneratingUnit", "VoltageLevel", "VsConverter", "WaveTrap", "WindGeneratingUnit", "WindPowerPlant"];
            if !allowed.contains(&ref_entry.element.type_name()) {
                violations.push(Violation {
                    object_id:   mrid.clone(),
                    rule_id:     "op452cpi:Control.PowerSystemResource-valueType".to_string(),
                    class:       "Control".to_string(),
                    property:    "Control.PowerSystemResource".to_string(),
                    message:     "One of the following does not conform: 1) The value type shall be IRI; 2) The value type is not an instance of the class PowerSystemResource or its subclass.".to_string(),
                    severity:    "sh:Violation".to_string(),
                    name:        "Control.PowerSystemResource-valueType".to_string(),
                    description: "This constraint validates the value type of the association at the used direction.".to_string(),
                });
            }
        }
    }
    violations
}

pub fn check_p61970_600_2_operation_ap_con_complex_implicit_crossprofile_shacl_measurement_measurement_t_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("Measurement").into_iter().flatten() {
        let entry = &dataset.entries[mrid];
        let obj = match entry.element.as_any()
            .downcast_ref::<cimstructs::Measurement>() {
            Some(o) => o, None => continue,
        };
        let ref_mrid = match obj.terminal.as_ref() {
            Some(r) => r.mrid.trim_start_matches('#'), None => continue,
        };
        if let Some(ref_entry) = dataset.entries.get(ref_mrid) {
            let allowed: &[&str] = &["ACDCConverterDCTerminal", "ACDCTerminal", "DCBaseTerminal", "DCTerminal", "Terminal"];
            if !allowed.contains(&ref_entry.element.type_name()) {
                violations.push(Violation {
                    object_id:   mrid.clone(),
                    rule_id:     "op452cpi:Measurement.ACDCTerminal-valueType".to_string(),
                    class:       "Measurement".to_string(),
                    property:    "Measurement.Terminal".to_string(),
                    message:     "One of the following does not conform: 1) The value type shall be IRI; 2) The value type is not an instance of the class PowerSystemResource or its subclass.".to_string(),
                    severity:    "sh:Violation".to_string(),
                    name:        "Measurement.ACDCTerminal-valueType".to_string(),
                    description: "This constraint validates the value type of the association at the used direction.".to_string(),
                });
            }
        }
    }
    violations
}

pub fn check_p61970_600_2_operation_ap_con_complex_implicit_crossprofile_shacl_measurement_measurement_p_etc(dataset: &CimDataset) -> Vec<Violation> {
    let mut violations = Vec::new();
    for mrid in dataset.by_type.get("Measurement").into_iter().flatten() {
        let entry = &dataset.entries[mrid];
        let obj = match entry.element.as_any()
            .downcast_ref::<cimstructs::Measurement>() {
            Some(o) => o, None => continue,
        };
        let ref_mrid = match obj.power_system_resource.as_ref() {
            Some(r) => r.mrid.trim_start_matches('#'), None => continue,
        };
        if let Some(ref_entry) = dataset.entries.get(ref_mrid) {
            let allowed: &[&str] = &["ACDCConverter", "ACLineSegment", "AsynchronousMachine", "AuxiliaryEquipment", "BatteryUnit", "Bay", "BoundaryPoint", "Breaker", "BusbarSection", "CAESPlant", "Clamp", "CogenerationPlant", "CombinedCyclePlant", "ConductingEquipment", "Conductor", "ConformLoad", "ConnectivityNodeContainer", "Connector", "ControlArea", "CsConverter", "CurrentTransformer", "Cut", "DCBreaker", "DCBusbar", "DCChopper", "DCConductingEquipment", "DCConverterUnit", "DCDisconnector", "DCEquipmentContainer", "DCGround", "DCLine", "DCLineSegment", "DCSeriesDevice", "DCShunt", "DCSwitch", "DisconnectingCircuitBreaker", "Disconnector", "EarthFaultCompensator", "EnergyConnection", "EnergyConsumer", "EnergySource", "Equipment", "EquipmentContainer", "EquivalentBranch", "EquivalentEquipment", "EquivalentInjection", "EquivalentNetwork", "EquivalentShunt", "ExternalNetworkInjection", "FaultIndicator", "Fuse", "GeneratingUnit", "Ground", "GroundDisconnector", "GroundingImpedance", "HydroGeneratingUnit", "HydroPowerPlant", "HydroPump", "Jumper", "Junction", "Line", "LinearShuntCompensator", "LoadBreakSwitch", "NonConformLoad", "NonlinearShuntCompensator", "NuclearGeneratingUnit", "PetersenCoil", "PhaseTapChanger", "PhaseTapChangerAsymmetrical", "PhaseTapChangerLinear", "PhaseTapChangerNonLinear", "PhaseTapChangerSymmetrical", "PhaseTapChangerTabular", "PhotoVoltaicUnit", "PostLineSensor", "PotentialTransformer", "PowerElectronicsConnection", "PowerElectronicsUnit", "PowerElectronicsWindUnit", "PowerSystemResource", "PowerTransformer", "ProtectedSwitch", "RatioTapChanger", "RegulatingCondEq", "RegulatingControl", "RotatingMachine", "Sensor", "SeriesCompensator", "ShuntCompensator", "SolarGeneratingUnit", "SolarPowerPlant", "StaticVarCompensator", "StationSupply", "Substation", "SurgeArrester", "Switch", "SynchronousMachine", "TapChanger", "TapChangerControl", "ThermalGeneratingUnit", "VoltageLevel", "VsConverter", "WaveTrap", "WindGeneratingUnit", "WindPowerPlant"];
            if !allowed.contains(&ref_entry.element.type_name()) {
                violations.push(Violation {
                    object_id:   mrid.clone(),
                    rule_id:     "op452cpi:Measurement.PowerSystemResource-valueType".to_string(),
                    class:       "Measurement".to_string(),
                    property:    "Measurement.PowerSystemResource".to_string(),
                    message:     "One of the following does not conform: 1) The value type shall be IRI; 2) The value type is not an instance of the class PowerSystemResource or its subclass.".to_string(),
                    severity:    "sh:Violation".to_string(),
                    name:        "Measurement.PowerSystemResource-valueType".to_string(),
                    description: "This constraint validates the value type of the association at the used direction.".to_string(),
                });
            }
        }
    }
    violations
}

