//! The IEC 61970/61968 Common Information Model as profiled by ENTSO-E CGMES
//! and the Network Code profiles: the streaming RDF/XML decoder that builds a
//! [`CimDataset`] of [`Element`]s, and conversion back to RDF/XML and to JSON.
//!
//! Elements are property bags. What each class declares comes from a class
//! table, generated by `cimgen` into `src/generated/` (gitignored; run
//! `make generate`) or read from RDFS at runtime ([`schema_source`]).
//! Everything else in `src/` is hand-written.

pub mod base;
pub mod convert;
pub mod decode;
pub mod registry;
pub mod schema_source;

mod generated;
pub use generated::*;

pub use base::{Element, FieldValue};
pub use decode::CimDataset;
