[package]
name = "cimoxide-validation"
description = "SHACL validation of CGMES datasets against the ENTSO-E profile constraints"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
include = ["src/**/*.rs", "Cargo.toml"]

[lib]
name = "cimvalidation"

[dependencies]
cimoxide-structs = { workspace = true }
cimoxide-decoder = { workspace = true }
regex       = "1"
