use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::Path;

use crate::generator::rust_gen::{sanitize_field, to_snake_case};
use crate::schema::model::{CimAttribute, CimSpecification};

use super::model::*;

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

pub fn generate_validation(
    results: &[FileResults],
    spec: &CimSpecification,
    output_dir: &Path,
) -> Result<usize, Box<dyn std::error::Error>> {
    fs::create_dir_all(output_dir)?;

    let mut total_checks = 0usize;
    let mut generated_modules: Vec<String> = Vec::new();

    for fr in results {
        let (code, count) = render_file(fr, spec);
        if count == 0 {
            continue;
        }
        total_checks += count;
        let mod_name = file_to_mod_name(&fr.file_name);
        let out_path = output_dir.join(format!("generated_{mod_name}.rs"));
        fs::write(&out_path, code)?;
        generated_modules.push(mod_name);
    }

    // Write a helper module to include from lib.rs
    let lib = render_lib_additions(&generated_modules);
    fs::write(output_dir.join("generated_lib.rs"), lib)?;

    Ok(total_checks)
}

// ---------------------------------------------------------------------------
// Per-file rendering
// ---------------------------------------------------------------------------

fn render_file(fr: &FileResults, spec: &CimSpecification) -> (String, usize) {
    let file_snake = file_to_mod_name(&fr.file_name);

    let mut regex_decls: Vec<String> = Vec::new();
    let mut regex_counter = 0usize;
    let mut check_names: Vec<String> = Vec::new();
    let mut checks_body = String::new();
    let mut used_fn_names: std::collections::HashSet<String> = std::collections::HashSet::new();

    for node_shape in &fr.shapes {
        for target in &node_shape.targets {
            let class_name = local_name(&target.value);
            if spec.types.get(&class_name).is_none() {
                continue; // class not in schema (e.g. md:FullModel)
            }

            for prop_shape in &node_shape.properties {
                if prop_shape.path.is_empty() {
                    continue;
                }
                for constraint in &prop_shape.constraints {
                    let (opt_code, opt_regex) = render_check(
                        &file_snake,
                        &class_name,
                        spec,
                        &prop_shape.path,
                        constraint,
                        &mut regex_counter,
                    );
                    if let Some(fn_code) = opt_code {
                        if let Some(decl) = opt_regex {
                            regex_decls.push(decl);
                        }
                        let raw_name = extract_fn_name(&fn_code);
                        // Deduplicate: if the name was already used (can happen after
                        // truncation), rename by appending a counter suffix.
                        let fn_name = if used_fn_names.contains(&raw_name) {
                            let mut n = 2usize;
                            loop {
                                let candidate = format!("{raw_name}_{n}");
                                if !used_fn_names.contains(&candidate) {
                                    break candidate;
                                }
                                n += 1;
                            }
                        } else {
                            raw_name.clone()
                        };
                        // Patch the fn name in the emitted code if it changed
                        let patched = if fn_name != raw_name {
                            fn_code.replacen(&format!("pub fn {raw_name}("), &format!("pub fn {fn_name}("), 1)
                        } else {
                            fn_code
                        };
                        used_fn_names.insert(fn_name.clone());
                        check_names.push(fn_name);
                        checks_body.push_str(&patched);
                        checks_body.push('\n');
                    }
                }
            }
        }
    }

    let count = check_names.len();
    if count == 0 {
        return (String::new(), 0);
    }

    let mut s = String::new();
    writeln!(s, "// Generated by cimgen — do not edit by hand.").unwrap();
    writeln!(s, "#![allow(clippy::all, dead_code, unused)]").unwrap();
    writeln!(s, "use cimdecoder::CimDataset;").unwrap();
    writeln!(s, "use crate::Violation;").unwrap();
    writeln!(s, "use crate::helpers::*;").unwrap();
    writeln!(s).unwrap();

    if !regex_decls.is_empty() {
        writeln!(s, "use std::sync::LazyLock;").unwrap();
        for decl in &regex_decls {
            s.push_str(decl);
            s.push('\n');
        }
        writeln!(s).unwrap();
    }

    let orchestrator = format!("validate_{file_snake}");
    writeln!(s, "pub fn {orchestrator}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut v = Vec::new();").unwrap();
    for name in &check_names {
        writeln!(s, "    v.extend({name}(dataset));").unwrap();
    }
    writeln!(s, "    v").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();

    s.push_str(&checks_body);

    (s, count)
}

// ---------------------------------------------------------------------------
// Per-constraint rendering
// ---------------------------------------------------------------------------

fn render_check(
    file_snake: &str,
    class_name: &str,
    spec: &CimSpecification,
    full_path: &[String],
    constraint: &ConstraintInfo,
    regex_counter: &mut usize,
) -> (Option<String>, Option<String>) {
    let path_seg = full_path[0].as_str();
    let attr_id = local_name(path_seg);
    let is_multi_seg = full_path.len() > 1;

    let comp = constraint.component.as_str();

    // Compute fn_name early so all branches can use it.
    let attr_part = to_snake_case(&attr_id.replace('.', "_"));
    let comp_suffix = component_suffix(comp);
    let raw_name = format!(
        "check_{file_snake}_{class_snake}_{attr_part}_{comp_suffix}",
        class_snake = to_snake_case(class_name),
    );
    let fn_name = safe_fn_name(&raw_name);

    // Multi-segment paths: handle [slice_field, rdf:type] for sh:In / sh:HasValue;
    // everything else is skipped.
    if is_multi_seg {
        if full_path.len() == 2 && full_path[1] == "rdf:type"
            && !path_seg.starts_with('~')
            && matches!(comp, "sh:InConstraintComponent" | "sh:HasValueConstraintComponent")
        {
            return gen_slice_mrid_rdf_type_check(&fn_name, class_name, spec, &attr_id, constraint);
        }
        return (None, None);
    }

    // Inverse path (encoded as "~<forward-iri>" by the parser) — route to dedicated generator
    // before the component skip list so MaxCount is not dropped for inverse shapes.
    if path_seg.starts_with('~') {
        let forward_pred = &path_seg[1..]; // strip "~"
        return gen_inverse_count(&fn_name, class_name, forward_pred, spec, constraint);
    }

    match comp {
        "sh:NodeKindConstraintComponent"
        | "sh:MaxCountConstraintComponent"
        | "sh:OrInversePathConstraintComponent" => return (None, None),
        _ => {}
    }

    let (accessor_prefix, attr) = match find_attr_in_hierarchy(spec, class_name, &attr_id) {
        Some(pair) => pair,
        None => return (None, None),
    };
    if !attr.is_association_used {
        return (None, None);
    }

    let field_name = sanitize_field(to_snake_case(&attr.label));
    let full_accessor = format!("{accessor_prefix}.{field_name}");

    match comp {
        "sh:RequiredConstraintComponent" | "sh:MinCountConstraintComponent" => {
            gen_required(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        "sh:ExactCountConstraintComponent" => {
            gen_exact_count(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        "sh:InConstraintComponent" => {
            gen_in(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        "sh:HasValueConstraintComponent" => {
            gen_has_value(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        "sh:DatatypeConstraintComponent" => {
            gen_datatype(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        "sh:PatternConstraintComponent" => {
            gen_pattern(&fn_name, class_name, &full_accessor, &attr, constraint, regex_counter)
        }
        "sh:MinLengthConstraintComponent" => {
            gen_length(&fn_name, class_name, &full_accessor, &attr, constraint, true)
        }
        "sh:MaxLengthConstraintComponent" => {
            gen_length(&fn_name, class_name, &full_accessor, &attr, constraint, false)
        }
        "sh:MinExclusiveConstraintComponent"
        | "sh:MaxExclusiveConstraintComponent"
        | "sh:MinInclusiveConstraintComponent"
        | "sh:MaxInclusiveConstraintComponent" => {
            gen_numeric_range(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        "sh:LessThanConstraintComponent" => {
            gen_less_than(&fn_name, class_name, spec, &full_accessor, &attr, constraint)
        }
        "sh:ClassConstraintComponent" => {
            gen_class(&fn_name, class_name, spec, &full_accessor, &attr, constraint)
        }
        "sh:OrClassConstraintComponent" => {
            gen_or_class(&fn_name, class_name, spec, &full_accessor, &attr, constraint)
        }
        "sh:NotClassConstraintComponent" => {
            gen_not_class(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        _ => (None, None),
    }
}

// ---------------------------------------------------------------------------
// Constraint generators
// ---------------------------------------------------------------------------

fn gen_required(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> (Option<String>, Option<String>) {
    let condition = if attr.is_list {
        format!("{accessor}.is_empty()")
    } else if attr.is_primitive || attr.is_cim_datatype {
        match attr.lang_type.as_str() {
            "String" => format!("{accessor}.is_empty()"),
            "bool" | "i64" | "f64" => format!("{accessor}.is_none()"),
            _ => format!("{accessor}.is_empty()"),
        }
    } else if attr.is_enum_value {
        format!("{accessor}.is_none()")
    } else {
        format!("{accessor}.is_none()")
    };
    (Some(build_fn(fn_name, class_name, None, None, &condition, c, attr)), None)
}

fn gen_exact_count(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> (Option<String>, Option<String>) {
    if !attr.is_list {
        return (None, None);
    }
    let n = c.payload.get("minCount").and_then(|v| v.as_int()).unwrap_or(1);
    let condition = format!("{accessor}.len() != {n}");
    (Some(build_fn(fn_name, class_name, None, None, &condition, c, attr)), None)
}

fn gen_in(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> (Option<String>, Option<String>) {
    if attr.is_list {
        if (attr.is_primitive || attr.is_cim_datatype) && attr.lang_type == "String" {
            return gen_slice_string_in(fn_name, class_name, accessor, attr, c);
        }
        return (None, None);
    }
    if (attr.is_primitive || attr.is_cim_datatype) && attr.lang_type != "String" {
        return (None, None);
    }
    let values = match c.payload.get("in").and_then(|v| v.as_list()) {
        Some(v) if !v.is_empty() => v,
        _ => return (None, None),
    };

    let allowed_items: Vec<String> = values
        .iter()
        .map(|v| format!("\"{}\"", v.replace('"', "\\\"")))
        .collect();
    let allowed_str = allowed_items.join(", ");

    let (field_expr, guard) = field_expr_and_guard(accessor, attr);
    let prelude = format!("    const ALLOWED: &[&str] = &[{allowed_str}];\n");
    let condition = format!("!ALLOWED.contains(&{field_expr})");

    (Some(build_fn(fn_name, class_name, guard.as_deref(), Some(&prelude), &condition, c, attr)), None)
}

fn gen_has_value(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> (Option<String>, Option<String>) {
    if attr.is_list { return (None, None); }
    if (attr.is_primitive || attr.is_cim_datatype) && attr.lang_type != "String" {
        return (None, None);
    }
    let expected = match c.payload.get("hasValue").and_then(|v| v.as_str()) {
        Some(v) => v.to_string(),
        None => return (None, None),
    };
    let esc = expected.replace('"', "\\\"");

    let (condition, guard) = if attr.is_enum_value {
        (format!("{accessor}.as_ref().map_or(true, |u| u.uri != \"{esc}\")"), None)
    } else if attr.is_primitive || attr.is_cim_datatype {
        (format!("{accessor} != \"{esc}\""),
         Some(format!("if {accessor}.is_empty() {{ continue; }}")))
    } else {
        (format!("{accessor}.as_ref().map_or(true, |r| r.mrid != \"{esc}\")"), None)
    };

    (Some(build_fn(fn_name, class_name, guard.as_deref(), None, &condition, c, attr)), None)
}

fn gen_datatype(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> (Option<String>, Option<String>) {
    if attr.lang_type != "String" {
        return (None, None);
    }
    let dt = c.payload.get("datatype").and_then(|v| v.as_str()).unwrap_or("");
    let check_fn = match dt {
        "xsd:dateTime" | "<http://www.w3.org/2001/XMLSchema#dateTime>" => "is_xsd_datetime",
        "xsd:date" | "<http://www.w3.org/2001/XMLSchema#date>" => "is_xsd_date",
        "xsd:gMonthDay" | "<http://www.w3.org/2001/XMLSchema#gMonthDay>" => "is_xsd_gmonthday",
        "xsd:anyURI" | "<http://www.w3.org/2001/XMLSchema#anyURI>" => "is_xsd_anyuri",
        _ => return (None, None),
    };
    let guard = format!("if {accessor}.is_empty() {{ continue; }}");
    let condition = format!("!{check_fn}(&{accessor})");
    (Some(build_fn(fn_name, class_name, Some(&guard), None, &condition, c, attr)), None)
}

fn gen_pattern(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
    regex_counter: &mut usize,
) -> (Option<String>, Option<String>) {
    if attr.lang_type != "String" {
        return (None, None);
    }
    let pattern = match c.payload.get("pattern").and_then(|v| v.as_str()) {
        Some(p) => p.to_string(),
        None => return (None, None),
    };
    let idx = *regex_counter;
    *regex_counter += 1;
    let static_name = format!("REGEX_{idx}");
    let escaped = pattern.replace('\\', "\\\\").replace('"', "\\\"");
    let regex_decl = format!(
        "static {static_name}: LazyLock<regex::Regex> = LazyLock::new(|| regex::Regex::new(\"{escaped}\").expect(\"SHACL regex\"));\n"
    );
    let guard = format!("if {accessor}.is_empty() {{ continue; }}");
    let condition = format!("!{static_name}.is_match(&{accessor})");
    (Some(build_fn(fn_name, class_name, Some(&guard), None, &condition, c, attr)), Some(regex_decl))
}

fn gen_length(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
    is_min: bool,
) -> (Option<String>, Option<String>) {
    if attr.lang_type != "String" {
        return (None, None);
    }
    let key = if is_min { "minLength" } else { "maxLength" };
    let n = match c.payload.get(key).and_then(|v| v.as_int()) {
        Some(n) => n,
        None => return (None, None),
    };
    let op = if is_min { "<" } else { ">" };
    let guard = format!("if {accessor}.is_empty() {{ continue; }}");
    let condition = format!("{accessor}.chars().count() {op} {n}");
    (Some(build_fn(fn_name, class_name, Some(&guard), None, &condition, c, attr)), None)
}

fn gen_numeric_range(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> (Option<String>, Option<String>) {
    let comp = c.component.as_str();
    let (key, op) = match comp {
        "sh:MinExclusiveConstraintComponent" => ("minExclusive", "<="),
        "sh:MaxExclusiveConstraintComponent" => ("maxExclusive", ">="),
        "sh:MinInclusiveConstraintComponent" => ("minInclusive", "<"),
        "sh:MaxInclusiveConstraintComponent" => ("maxInclusive", ">"),
        _ => return (None, None),
    };
    let val = match c.payload.get(key).and_then(|v| v.as_float()) {
        Some(f) => f,
        None => return (None, None),
    };
    let (guard, condition) = match attr.lang_type.as_str() {
        "f64" => (
            format!("if {accessor}.is_none() {{ continue; }}"),
            format!("{accessor}.unwrap() {op} {val}_f64"),
        ),
        "i64" => (
            format!("if {accessor}.is_none() {{ continue; }}"),
            format!("({accessor}.unwrap() as f64) {op} {val}_f64"),
        ),
        _ => return (None, None),
    };
    (Some(build_fn(fn_name, class_name, Some(&guard), None, &condition, c, attr)), None)
}

fn gen_less_than(
    fn_name: &str,
    class_name: &str,
    spec: &CimSpecification,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> (Option<String>, Option<String>) {
    if !matches!(attr.lang_type.as_str(), "f64" | "i64") {
        return (None, None);
    }
    let other_iri = match c.payload.get("lessThan").and_then(|v| v.as_str()) {
        Some(v) => v.to_string(),
        None => return (None, None),
    };
    let other_attr_id = local_name(&other_iri);
    let (other_prefix, other_attr) = match find_attr_in_hierarchy(spec, class_name, &other_attr_id) {
        Some(p) => p,
        None => return (None, None),
    };
    if !matches!(other_attr.lang_type.as_str(), "f64" | "i64") {
        return (None, None);
    }
    let other_field = sanitize_field(to_snake_case(&other_attr.label));
    let other_accessor = format!("{other_prefix}.{other_field}");

    let mut s = String::new();
    fn esc(x: &str) -> String { x.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop = &attr.id;

    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
    writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
    writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
    writeln!(s, "            Some(o) => o, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();
    writeln!(s, "        if {accessor}.is_none() || {other_accessor}.is_none() {{ continue; }}").unwrap();
    writeln!(s, "        if !(({accessor}.unwrap() as f64) < {other_accessor}.unwrap() as f64) {{").unwrap();
    writeln!(s, "            violations.push(Violation {{").unwrap();
    writeln!(s, "                object_id:   mrid.clone(),").unwrap();
    writeln!(s, "                rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                class:       \"{class_name}\".to_string(),").unwrap();
    writeln!(s, "                property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "                message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "                severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "                name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "            }});").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    (Some(s), None)
}

fn gen_not_class(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> (Option<String>, Option<String>) {
    if attr.is_primitive || attr.is_cim_datatype || attr.is_enum_value || attr.is_list {
        return (None, None);
    }
    let forbidden = match c.payload.get("class").and_then(|v| v.as_str()) {
        Some(v) => local_name(v),
        None => return (None, None),
    };

    let mut s = String::new();
    fn esc(x: &str) -> String { x.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop = &attr.id;

    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
    writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
    writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
    writeln!(s, "            Some(o) => o, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();
    writeln!(s, "        let ref_mrid = match {accessor}.as_ref() {{").unwrap();
    writeln!(s, "            Some(r) => &r.mrid, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();
    writeln!(s, "        if let Some(ref_entry) = dataset.entries.get(ref_mrid) {{").unwrap();
    writeln!(s, "            if ref_entry.element.type_name() == \"{forbidden}\" {{").unwrap();
    writeln!(s, "                violations.push(Violation {{").unwrap();
    writeln!(s, "                    object_id:   mrid.clone(),").unwrap();
    writeln!(s, "                    rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                    class:       \"{class_name}\".to_string(),").unwrap();
    writeln!(s, "                    property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "                    message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "                    severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "                    name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                    description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "                }});").unwrap();
    writeln!(s, "            }}").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    (Some(s), None)
}

fn gen_class(
    fn_name: &str,
    class_name: &str,
    spec: &CimSpecification,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> (Option<String>, Option<String>) {
    if attr.is_primitive || attr.is_cim_datatype || attr.is_enum_value {
        return (None, None);
    }
    let wanted = match c.payload.get("class").and_then(|v| v.as_str()) {
        Some(v) => local_name(v),
        None => return (None, None),
    };
    // Expand to all types that ARE or inherit from `wanted`. If everything
    // qualifies, the constraint is vacuously true and can be skipped.
    let allowed_types = class_and_subclasses(spec, &wanted);
    if allowed_types.is_empty() || allowed_types.len() >= spec.types.len() {
        return (None, None);
    }
    gen_ref_type_check(fn_name, class_name, accessor, attr, c, &allowed_types)
}

fn gen_or_class(
    fn_name: &str,
    class_name: &str,
    spec: &CimSpecification,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> (Option<String>, Option<String>) {
    if attr.is_primitive || attr.is_cim_datatype || attr.is_enum_value {
        return (None, None);
    }
    let raw_classes: Vec<String> = match c.payload.get("classes").and_then(|v| v.as_list()) {
        Some(v) if !v.is_empty() => v.iter().map(|s| local_name(s)).collect(),
        _ => return (None, None),
    };
    // Expand each listed class to include its subclasses.
    let mut allowed_set = std::collections::BTreeSet::new();
    for cls in &raw_classes {
        for t in class_and_subclasses(spec, cls) {
            allowed_set.insert(t);
        }
    }
    let allowed_types: Vec<String> = allowed_set.into_iter().collect();
    if allowed_types.is_empty() || allowed_types.len() >= spec.types.len() {
        return (None, None);
    }
    gen_ref_type_check(fn_name, class_name, accessor, attr, c, &allowed_types)
}

fn gen_ref_type_check(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
    allowed_types: &[String],
) -> (Option<String>, Option<String>) {
    fn esc(x: &str) -> String { x.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop = &attr.id;
    let allowed_str = allowed_types.iter()
        .map(|t| format!("\"{}\"", t))
        .collect::<Vec<_>>()
        .join(", ");

    let mut s = String::new();
    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
    writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
    writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
    writeln!(s, "            Some(o) => o, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();

    if attr.is_list {
        writeln!(s, "        for r in &{accessor} {{").unwrap();
        writeln!(s, "            let ref_id = r.mrid.trim_start_matches('#');").unwrap();
        writeln!(s, "            if ref_id.is_empty() {{ continue; }}").unwrap();
        writeln!(s, "            if let Some(ref_entry) = dataset.entries.get(ref_id) {{").unwrap();
        writeln!(s, "                let allowed: &[&str] = &[{allowed_str}];").unwrap();
        writeln!(s, "                if !allowed.contains(&ref_entry.element.type_name()) {{").unwrap();
        writeln!(s, "                    violations.push(Violation {{").unwrap();
        writeln!(s, "                        object_id:   mrid.clone(),").unwrap();
        writeln!(s, "                        rule_id:     \"{name_str}\".to_string(),").unwrap();
        writeln!(s, "                        class:       \"{class_name}\".to_string(),").unwrap();
        writeln!(s, "                        property:    \"{prop}\".to_string(),").unwrap();
        writeln!(s, "                        message:     \"{message}\".to_string(),").unwrap();
        writeln!(s, "                        severity:    \"{severity}\".to_string(),").unwrap();
        writeln!(s, "                        name:        \"{name_str}\".to_string(),").unwrap();
        writeln!(s, "                        description: \"{desc_str}\".to_string(),").unwrap();
        writeln!(s, "                    }});").unwrap();
        writeln!(s, "                }}").unwrap();
        writeln!(s, "            }}").unwrap();
        writeln!(s, "        }}").unwrap();
    } else {
        writeln!(s, "        let ref_mrid = match {accessor}.as_ref() {{").unwrap();
        writeln!(s, "            Some(r) => r.mrid.trim_start_matches('#'), None => continue,").unwrap();
        writeln!(s, "        }};").unwrap();
        writeln!(s, "        if let Some(ref_entry) = dataset.entries.get(ref_mrid) {{").unwrap();
        writeln!(s, "            let allowed: &[&str] = &[{allowed_str}];").unwrap();
        writeln!(s, "            if !allowed.contains(&ref_entry.element.type_name()) {{").unwrap();
        writeln!(s, "                violations.push(Violation {{").unwrap();
        writeln!(s, "                    object_id:   mrid.clone(),").unwrap();
        writeln!(s, "                    rule_id:     \"{name_str}\".to_string(),").unwrap();
        writeln!(s, "                    class:       \"{class_name}\".to_string(),").unwrap();
        writeln!(s, "                    property:    \"{prop}\".to_string(),").unwrap();
        writeln!(s, "                    message:     \"{message}\".to_string(),").unwrap();
        writeln!(s, "                    severity:    \"{severity}\".to_string(),").unwrap();
        writeln!(s, "                    name:        \"{name_str}\".to_string(),").unwrap();
        writeln!(s, "                    description: \"{desc_str}\".to_string(),").unwrap();
        writeln!(s, "                }});").unwrap();
        writeln!(s, "            }}").unwrap();
        writeln!(s, "        }}").unwrap();
    }

    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    (Some(s), None)
}

fn gen_slice_mrid_rdf_type_check(
    fn_name: &str,
    class_name: &str,
    spec: &CimSpecification,
    attr_id: &str,
    c: &ConstraintInfo,
) -> (Option<String>, Option<String>) {
    let (accessor_prefix, attr) = match find_attr_in_hierarchy(spec, class_name, attr_id) {
        Some(p) => p,
        None => return (None, None),
    };
    if !attr.is_list || attr.is_primitive || attr.is_cim_datatype || attr.is_enum_value || !attr.is_association_used {
        return (None, None);
    }
    let field_name = sanitize_field(to_snake_case(&attr.label));
    let accessor = format!("{accessor_prefix}.{field_name}");

    let comp = c.component.as_str();
    let allowed_types: Vec<String> = match comp {
        "sh:InConstraintComponent" => {
            match c.payload.get("in").and_then(|v| v.as_list()) {
                Some(v) if !v.is_empty() => v.iter().map(|s| local_name(s)).collect(),
                _ => return (None, None),
            }
        }
        "sh:HasValueConstraintComponent" => {
            match c.payload.get("hasValue").and_then(|v| v.as_str()) {
                Some(v) => vec![local_name(v)],
                None => return (None, None),
            }
        }
        _ => return (None, None),
    };
    if allowed_types.is_empty() {
        return (None, None);
    }
    let allowed_str = allowed_types.iter()
        .map(|t| format!("\"{t}\""))
        .collect::<Vec<_>>()
        .join(", ");

    fn esc(x: &str) -> String { x.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop = &attr.id;

    let mut s = String::new();
    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
    writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
    writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
    writeln!(s, "            Some(o) => o, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();
    writeln!(s, "        for r in &{accessor} {{").unwrap();
    writeln!(s, "            let ref_id = r.mrid.trim_start_matches('#');").unwrap();
    writeln!(s, "            if ref_id.is_empty() {{ continue; }}").unwrap();
    writeln!(s, "            if let Some(ref_entry) = dataset.entries.get(ref_id) {{").unwrap();
    writeln!(s, "                let allowed: &[&str] = &[{allowed_str}];").unwrap();
    writeln!(s, "                if !allowed.contains(&ref_entry.element.type_name()) {{").unwrap();
    writeln!(s, "                    violations.push(Violation {{").unwrap();
    writeln!(s, "                        object_id:   mrid.clone(),").unwrap();
    writeln!(s, "                        rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                        class:       \"{class_name}\".to_string(),").unwrap();
    writeln!(s, "                        property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "                        message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "                        severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "                        name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                        description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "                    }});").unwrap();
    writeln!(s, "                }}").unwrap();
    writeln!(s, "            }}").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    (Some(s), None)
}

fn gen_slice_string_in(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> (Option<String>, Option<String>) {
    let values = match c.payload.get("in").and_then(|v| v.as_list()) {
        Some(v) if !v.is_empty() => v,
        _ => return (None, None),
    };
    let allowed_items: Vec<String> = values
        .iter()
        .map(|v| format!("\"{}\"", v.replace('"', "\\\"")))
        .collect();
    let allowed_str = allowed_items.join(", ");

    fn esc(x: &str) -> String { x.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop = &attr.id;

    let mut s = String::new();
    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
    writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
    writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
    writeln!(s, "            Some(o) => o, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();
    writeln!(s, "        let allowed: &[&str] = &[{allowed_str}];").unwrap();
    writeln!(s, "        for val in &{accessor} {{").unwrap();
    writeln!(s, "            if val.is_empty() {{ continue; }}").unwrap();
    writeln!(s, "            if !allowed.contains(&val.as_str()) {{").unwrap();
    writeln!(s, "                violations.push(Violation {{").unwrap();
    writeln!(s, "                    object_id:   mrid.clone(),").unwrap();
    writeln!(s, "                    rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                    class:       \"{class_name}\".to_string(),").unwrap();
    writeln!(s, "                    property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "                    message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "                    severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "                    name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                    description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "                }});").unwrap();
    writeln!(s, "            }}").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    (Some(s), None)
}

// ---------------------------------------------------------------------------
// Inverse path generator
// ---------------------------------------------------------------------------

fn gen_inverse_count(
    fn_name: &str,
    target_class: &str,
    forward_pred: &str,
    spec: &CimSpecification,
    c: &ConstraintInfo,
) -> (Option<String>, Option<String>) {
    let local = local_name(forward_pred);
    let (src_class, src_prop) = match local.split_once('.') {
        Some(p) => p,
        None => return (None, None),
    };

    let (obj_prefix, attr) = match find_attr_in_hierarchy(spec, src_class, &local) {
        Some(p) => p,
        None => return (None, None),
    };
    if !attr.is_association_used { return (None, None); }
    // Inverse path requires an association field (Option<MridRef> or Vec<MridRef>)
    if attr.is_primitive || attr.is_cim_datatype || attr.is_enum_value { return (None, None); }

    let field_name = sanitize_field(to_snake_case(src_prop));
    let src_prefix = obj_prefix.replacen("obj", "src", 1);
    let src_field  = format!("{src_prefix}.{field_name}");

    let index_snippet = if attr.is_list {
        format!("for r in &{src_field} {{ *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }}")
    } else {
        format!("if let Some(r) = &{src_field} {{ *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }}")
    };

    let (op, threshold) = match c.component.as_str() {
        "sh:MinCountConstraintComponent" | "sh:RequiredConstraintComponent" =>
            ("<", c.payload.get("minCount").and_then(|v| v.as_int()).unwrap_or(1)),
        "sh:MaxCountConstraintComponent" =>
            (">", c.payload.get("maxCount").and_then(|v| v.as_int()).unwrap_or(1)),
        _ => return (None, None),
    };

    (Some(build_inverse_fn(fn_name, target_class, src_class, &index_snippet, threshold, op, c)), None)
}

fn build_inverse_fn(
    fn_name: &str,
    target_class: &str,
    src_class: &str,
    index_snippet: &str,
    threshold: i64,
    op: &str,
    c: &ConstraintInfo,
) -> String {
    let mut s = String::new();
    fn esc(x: &str) -> String { x.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop     = &c.name;

    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();").unwrap();
    writeln!(s, "    for src_mrid in dataset.by_type.get(\"{src_class}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        if let Some(src) = dataset.entries.get(src_mrid)").unwrap();
    writeln!(s, "            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::{src_class}>()) {{").unwrap();
    writeln!(s, "            {index_snippet}").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{target_class}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);").unwrap();
    writeln!(s, "        if count {op} {threshold} {{").unwrap();
    writeln!(s, "            violations.push(Violation {{").unwrap();
    writeln!(s, "                object_id:   mrid.clone(),").unwrap();
    writeln!(s, "                rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                class:       \"{target_class}\".to_string(),").unwrap();
    writeln!(s, "                property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "                message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "                severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "                name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "            }});").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    s
}

// ---------------------------------------------------------------------------
// Code-building helpers
// ---------------------------------------------------------------------------

fn field_expr_and_guard(accessor: &str, attr: &CimAttribute) -> (String, Option<String>) {
    if attr.is_enum_value {
        (
            format!("{accessor}.as_ref().map_or(\"\", |u| u.uri.as_str())"),
            Some(format!("if {accessor}.is_none() {{ continue; }}")),
        )
    } else if attr.is_primitive || attr.is_cim_datatype {
        (
            format!("{accessor}.as_str()"),
            Some(format!("if {accessor}.is_empty() {{ continue; }}")),
        )
    } else {
        (
            format!("{accessor}.as_ref().map_or(\"\", |r| r.mrid.as_str())"),
            Some(format!("if {accessor}.is_none() {{ continue; }}")),
        )
    }
}

fn build_fn(
    fn_name: &str,
    class_name: &str,
    guard: Option<&str>,
    prelude: Option<&str>,     // constant decls outside the loop
    condition: &str,
    c: &ConstraintInfo,
    attr: &CimAttribute,
) -> String {
    let mut s = String::new();
    let prop = &attr.id;
    fn esc(s: &str) -> String { s.replace('\\', "\\\\").replace('"', "\\\"") }
    let message = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);

    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    // Prelude goes BEFORE the loop (constants, regex etc.)
    if let Some(pre) = prelude {
        s.push_str(pre);
    }
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
    writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
    writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
    writeln!(s, "            Some(o) => o, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();
    if let Some(g) = guard {
        writeln!(s, "        {g}").unwrap();
    }
    writeln!(s, "        if {condition} {{").unwrap();
    writeln!(s, "            violations.push(Violation {{").unwrap();
    writeln!(s, "                object_id:   mrid.clone(),").unwrap();
    writeln!(s, "                rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                class:       \"{class_name}\".to_string(),").unwrap();
    writeln!(s, "                property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "                message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "                severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "                name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "            }});").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    s
}

// ---------------------------------------------------------------------------
// Field lookup
// ---------------------------------------------------------------------------

fn find_attr_in_hierarchy(
    spec: &CimSpecification,
    class_name: &str,
    attr_id: &str,
) -> Option<(String, CimAttribute)> {
    let mut depth = 0usize;
    let mut current_id = class_name.to_string();
    loop {
        let t = spec.types.get(&current_id)?;
        if let Some(attr) = t.attributes.iter().find(|a| a.id == attr_id) {
            // depth 0 → "obj", depth 1 → "obj.base", depth 2 → "obj.base.base"
            let prefix = format!("obj{}", ".base".repeat(depth));
            return Some((prefix, attr.clone()));
        }
        if t.super_type.is_empty() || t.super_type == current_id {
            break;
        }
        depth += 1;
        current_id = t.super_type.clone();
    }
    None
}

// ---------------------------------------------------------------------------
// lib / module helpers
// ---------------------------------------------------------------------------

fn render_lib_additions(modules: &[String]) -> String {
    let mut s = String::new();
    writeln!(s, "// Generated module declarations — include this file from lib.rs.").unwrap();
    writeln!(s, "pub mod helpers;").unwrap();
    for m in modules {
        writeln!(s, "pub mod generated_{m};").unwrap();
    }
    writeln!(s).unwrap();
    writeln!(s, "pub fn validate_generated(dataset: &cimdecoder::CimDataset, profiles: &[&str]) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut v = Vec::new();").unwrap();
    for m in modules {
        let fn_name = format!("generated_{m}::validate_{m}");
        if let Some(p) = guess_profile_from_mod(m) {
            writeln!(s, "    if profiles.contains(&\"{p}\") {{").unwrap();
            writeln!(s, "        v.extend({fn_name}(dataset));").unwrap();
            writeln!(s, "    }}").unwrap();
        } else {
            writeln!(s, "    v.extend({fn_name}(dataset));").unwrap();
        }
    }
    writeln!(s, "    v").unwrap();
    writeln!(s, "}}").unwrap();
    s
}

// ---------------------------------------------------------------------------
// Name helpers
// ---------------------------------------------------------------------------

fn local_name(simplified_iri: &str) -> String {
    if let Some(colon) = simplified_iri.find(':') {
        simplified_iri[colon + 1..].to_string()
    } else {
        simplified_iri.to_string()
    }
}

/// Convert a TTL file name to a valid Rust module name.
fn file_to_mod_name(file_name: &str) -> String {
    let raw: String = file_name
        .chars()
        .map(|c| if c.is_alphanumeric() { c.to_ascii_lowercase() } else { '_' })
        .collect();
    // Module names can't start with a digit
    let raw = raw.trim_matches('_');
    if raw.starts_with(|c: char| c.is_ascii_digit()) {
        format!("p{raw}")
    } else {
        raw.to_string()
    }
}

fn component_suffix(component: &str) -> &str {
    match component {
        "sh:RequiredConstraintComponent" => "required",
        "sh:MinCountConstraintComponent" => "min_count",
        "sh:MaxCountConstraintComponent" => "max_count",
        "sh:ExactCountConstraintComponent" => "exact_count",
        "sh:InConstraintComponent" => "in",
        "sh:HasValueConstraintComponent" => "has_value",
        "sh:DatatypeConstraintComponent" => "datatype",
        "sh:ClassConstraintComponent" => "class_check",
        "sh:OrClassConstraintComponent" => "or_class",
        "sh:NotClassConstraintComponent" => "not_class",
        "sh:LessThanConstraintComponent" => "less_than",
        "sh:PatternConstraintComponent" => "pattern",
        "sh:MinLengthConstraintComponent" => "min_length",
        "sh:MaxLengthConstraintComponent" => "max_length",
        "sh:MinExclusiveConstraintComponent" => "min_excl",
        "sh:MaxExclusiveConstraintComponent" => "max_excl",
        "sh:MinInclusiveConstraintComponent" => "min_incl",
        "sh:MaxInclusiveConstraintComponent" => "max_incl",
        _ => "constraint",
    }
}

fn safe_fn_name(raw: &str) -> String {
    // Collapse runs of underscores, ensure doesn't start with digit
    let collapsed: String = {
        let mut prev = '_';
        let mut s = String::new();
        for c in raw.chars() {
            if c == '_' && prev == '_' { continue; }
            s.push(c);
            prev = c;
        }
        s.trim_matches('_').to_string()
    };
    if collapsed.starts_with(|c: char| c.is_ascii_digit()) {
        format!("check_{collapsed}")
    } else if collapsed.len() > 100 {
        format!("{}_etc", collapsed[..97].trim_end_matches('_'))
    } else {
        collapsed
    }
}

fn extract_fn_name(code: &str) -> String {
    code.lines()
        .find(|l| l.starts_with("pub fn "))
        .and_then(|l| l.strip_prefix("pub fn "))
        .and_then(|l| l.split('(').next())
        .unwrap_or("")
        .to_string()
}

fn guess_profile_from_mod(mod_name: &str) -> Option<&'static str> {
    let m = mod_name.to_lowercase();
    if m.contains("equipmentboundary") { Some("EQBD") }
    else if m.contains("equipment") { Some("EQ") }
    else if m.contains("steadystatehypothesis") { Some("SSH") }
    else if m.contains("topology") { Some("TP") }
    else if m.contains("statevariables") { Some("SV") }
    else if m.contains("dynamics") { Some("DY") }
    else if m.contains("shortcircuit") { Some("SC") }
    else if m.contains("diagramlayout") { Some("DL") }
    else if m.contains("geographicallocation") { Some("GL") }
    else if m.contains("operation") { Some("OP") }
    else { None }
}

// ---------------------------------------------------------------------------
// Class hierarchy helpers
// ---------------------------------------------------------------------------

fn is_subtype_of(spec: &CimSpecification, type_name: &str, ancestor: &str) -> bool {
    let mut current = type_name.to_string();
    let mut visited = std::collections::HashSet::new();
    loop {
        if !visited.insert(current.clone()) {
            return false;
        }
        match spec.types.get(&current) {
            Some(t) => {
                if t.super_type.is_empty() || t.super_type == current {
                    return false;
                }
                if t.super_type == ancestor {
                    return true;
                }
                current = t.super_type.clone();
            }
            None => return false,
        }
    }
}

fn class_and_subclasses(spec: &CimSpecification, class: &str) -> Vec<String> {
    let mut result: Vec<String> = spec.types
        .keys()
        .filter(|name| name.as_str() == class || is_subtype_of(spec, name, class))
        .cloned()
        .collect();
    result.sort();
    result
}

// ---------------------------------------------------------------------------
// Shared runtime helpers (written to helpers.rs in the output crate)
// ---------------------------------------------------------------------------

