use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::Path;

use crate::generator::rust_gen::{sanitize_field, to_snake_case};
use crate::schema::model::{CimAttribute, CimSpecification};

use super::model::*;
use super::skip;

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

pub fn generate_validation(
    results: &[FileResults],
    spec: &CimSpecification,
    output_dir: &Path,
) -> Result<(usize, Vec<skip::FileSkipInfo>), Box<dyn std::error::Error>> {
    fs::create_dir_all(output_dir)?;

    let mut total_checks = 0usize;
    let mut generated_modules: Vec<String> = Vec::new();
    let mut file_skips: Vec<skip::FileSkipInfo> = Vec::new();

    for fr in results {
        let (code, count, skips) = render_file(fr, spec);
        let mod_name = file_to_mod_name(&fr.file_name);
        file_skips.push(skip::FileSkipInfo { file_name: fr.file_name.clone(), check_count: count, skips });
        if count == 0 {
            continue;
        }
        total_checks += count;
        let out_path = output_dir.join(format!("generated_{mod_name}.rs"));
        fs::write(&out_path, code)?;
        generated_modules.push(mod_name);
    }

    Ok((total_checks, file_skips))
}

// ---------------------------------------------------------------------------
// Per-file rendering
// ---------------------------------------------------------------------------

fn render_file(fr: &FileResults, spec: &CimSpecification) -> (String, usize, Vec<skip::SkipEntry>) {
    let file_snake = file_to_mod_name(&fr.file_name);

    let mut regex_decls: Vec<String> = Vec::new();
    let mut regex_counter = 0usize;
    let mut check_names: Vec<String> = Vec::new();
    let mut checks_body = String::new();
    let mut used_fn_names: std::collections::HashSet<String> = std::collections::HashSet::new();
    let mut collector = skip::SkipCollector::new();

    for node_shape in &fr.shapes {
        for target in &node_shape.targets {
            let class_name = local_name(&target.value);
            if spec.types.get(&class_name).is_none() {
                continue; // class not in schema (e.g. md:FullModel)
            }

            // Compound node-level constraints (sh:xone, sh:or, sh:and)
            for node_constraint in &node_shape.constraints {
                match gen_compound_check(&file_snake, &class_name, spec, node_constraint) {
                    Ok(fn_code) => {
                        let raw_name = extract_fn_name(&fn_code);
                        let fn_name = dedup_fn_name(raw_name.clone(), &used_fn_names);
                        let patched = if fn_name != raw_name {
                            fn_code.replacen(&format!("pub fn {raw_name}("), &format!("pub fn {fn_name}("), 1)
                        } else { fn_code };
                        used_fn_names.insert(fn_name.clone());
                        check_names.push(fn_name);
                        checks_body.push_str(&patched);
                        checks_body.push('\n');
                    }
                    Err(reason) => {
                        collector.push(&class_name, "", &node_constraint.component, &node_constraint.name, &reason);
                    }
                }
            }

            for prop_shape in &node_shape.properties {
                if prop_shape.path.is_empty() {
                    continue;
                }
                for constraint in &prop_shape.constraints {
                    let (opt_code, opt_regex) = render_check(
                        &file_snake,
                        &class_name,
                        spec,
                        &prop_shape.path,
                        constraint,
                        &mut regex_counter,
                        &mut collector,
                    );
                    if let Some(fn_code) = opt_code {
                        if let Some(decl) = opt_regex {
                            regex_decls.push(decl);
                        }
                        let raw_name = extract_fn_name(&fn_code);
                        let fn_name = dedup_fn_name(raw_name.clone(), &used_fn_names);
                        let patched = if fn_name != raw_name {
                            fn_code.replacen(&format!("pub fn {raw_name}("), &format!("pub fn {fn_name}("), 1)
                        } else { fn_code };
                        used_fn_names.insert(fn_name.clone());
                        check_names.push(fn_name);
                        checks_body.push_str(&patched);
                        checks_body.push('\n');
                    }
                }
            }
        }
    }

    let count = check_names.len();
    if count == 0 {
        return (String::new(), 0, collector.into_entries());
    }

    let mut s = String::new();
    writeln!(s, "// Generated by cimgen — do not edit by hand.").unwrap();
    writeln!(s, "#![allow(clippy::all, dead_code, unused)]").unwrap();
    writeln!(s, "use cimdecoder::CimDataset;").unwrap();
    writeln!(s, "use crate::Violation;").unwrap();
    writeln!(s, "use crate::helpers::*;").unwrap();
    writeln!(s).unwrap();

    if !regex_decls.is_empty() {
        writeln!(s, "use std::sync::LazyLock;").unwrap();
        for decl in &regex_decls {
            s.push_str(decl);
            s.push('\n');
        }
        writeln!(s).unwrap();
    }

    let orchestrator = format!("validate_{file_snake}");
    writeln!(s, "pub fn {orchestrator}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut v = Vec::new();").unwrap();
    for name in &check_names {
        writeln!(s, "    v.extend({name}(dataset));").unwrap();
    }
    writeln!(s, "    v").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();

    s.push_str(&checks_body);

    (s, count, collector.into_entries())
}

// ---------------------------------------------------------------------------
// Per-constraint rendering
// ---------------------------------------------------------------------------

fn render_check(
    file_snake: &str,
    class_name: &str,
    spec: &CimSpecification,
    full_path: &[String],
    constraint: &ConstraintInfo,
    regex_counter: &mut usize,
    collector: &mut skip::SkipCollector,
) -> (Option<String>, Option<String>) {
    let path_seg = full_path[0].as_str();
    let attr_id = local_name(path_seg);
    let is_multi_seg = full_path.len() > 1;

    let comp = constraint.component.as_str();

    // Compute fn_name early so all branches can use it.
    let attr_part = to_snake_case(&attr_id.replace('.', "_"));
    let comp_suffix = component_suffix(comp);
    let raw_name = format!(
        "check_{file_snake}_{class_snake}_{attr_part}_{comp_suffix}",
        class_snake = to_snake_case(class_name),
    );
    let fn_name = safe_fn_name(&raw_name);

    // Multi-segment paths: handle [slice_field, rdf:type] for sh:In / sh:HasValue;
    // everything else is skipped.
    if is_multi_seg {
        if full_path.len() == 2 && full_path[1] == "rdf:type"
            && !path_seg.starts_with('~')
            && matches!(comp, "sh:InConstraintComponent" | "sh:HasValueConstraintComponent")
        {
            return match gen_slice_mrid_rdf_type_check(&fn_name, class_name, spec, &attr_id, constraint) {
                Ok((code, regex)) => (Some(code), regex),
                Err(reason) => {
                    collector.push(class_name, path_seg, comp, &constraint.name, &reason);
                    (None, None)
                }
            };
        }
        collector.push(class_name, path_seg, comp, &constraint.name, "multi-segment path not supported");
        return (None, None);
    }

    // Inverse path (encoded as "~<forward-iri>" by the parser) — route to dedicated generator
    // before the component skip list so MaxCount is not dropped for inverse shapes.
    if path_seg.starts_with('~') {
        let forward_pred = &path_seg[1..]; // strip "~"
        return match gen_inverse_count(&fn_name, class_name, forward_pred, spec, constraint) {
            Ok((code, regex)) => (Some(code), regex),
            Err(reason) => {
                collector.push(class_name, path_seg, comp, &constraint.name, &reason);
                (None, None)
            }
        };
    }

    match comp {
        "sh:NodeKindConstraintComponent" => {
            collector.push(class_name, path_seg, comp, &constraint.name,
                "sh:NodeKindConstraintComponent structurally satisfied by Rust type system");
            return (None, None);
        }
        "sh:SPARQLConstraintComponent" => {
            collector.push(class_name, path_seg, comp, &constraint.name,
                "sh:SPARQLConstraintComponent: no SPARQL evaluator");
            return (None, None);
        }
        "sh:OrInversePathConstraintComponent" => {
            collector.push(class_name, path_seg, comp, &constraint.name,
                "sh:OrInversePathConstraintComponent structurally satisfied");
            return (None, None);
        }
        _ => {}
    }

    let (accessor_prefix, attr) = match find_attr_in_hierarchy(spec, class_name, &attr_id) {
        Some(pair) => pair,
        None => {
            collector.push(class_name, path_seg, comp, &constraint.name,
                &format!("attribute {} not found in hierarchy", attr_id));
            return (None, None);
        }
    };
    if !attr.is_association_used {
        collector.push(class_name, path_seg, comp, &constraint.name, "unused association");
        return (None, None);
    }

    let field_name = sanitize_field(to_snake_case(&attr.label));
    let full_accessor = format!("{accessor_prefix}.{field_name}");

    let result = match comp {
        "sh:RequiredConstraintComponent" | "sh:MinCountConstraintComponent" => {
            gen_required(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        "sh:MaxCountConstraintComponent" => {
            gen_max_count_one(&fn_name, class_name, &attr_id, &attr, constraint)
        }
        "sh:ExactCountConstraintComponent" => {
            gen_exact_count(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        "sh:InConstraintComponent" => {
            gen_in(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        "sh:HasValueConstraintComponent" => {
            gen_has_value(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        "sh:DatatypeConstraintComponent" => {
            gen_datatype(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        "sh:PatternConstraintComponent" => {
            gen_pattern(&fn_name, class_name, &full_accessor, &attr, constraint, regex_counter)
        }
        "sh:MinLengthConstraintComponent" => {
            gen_length(&fn_name, class_name, &full_accessor, &attr, constraint, true)
        }
        "sh:MaxLengthConstraintComponent" => {
            gen_length(&fn_name, class_name, &full_accessor, &attr, constraint, false)
        }
        "sh:MinExclusiveConstraintComponent"
        | "sh:MaxExclusiveConstraintComponent"
        | "sh:MinInclusiveConstraintComponent"
        | "sh:MaxInclusiveConstraintComponent" => {
            gen_numeric_range(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        "sh:LessThanConstraintComponent" => {
            gen_less_than(&fn_name, class_name, spec, &full_accessor, &attr, constraint)
        }
        "sh:ClassConstraintComponent" => {
            gen_class(&fn_name, class_name, spec, &full_accessor, &attr, constraint)
        }
        "sh:OrClassConstraintComponent" => {
            gen_or_class(&fn_name, class_name, spec, &full_accessor, &attr, constraint)
        }
        "sh:NotClassConstraintComponent" => {
            gen_not_class(&fn_name, class_name, &full_accessor, &attr, constraint)
        }
        _ => Err(format!("unknown component: {comp}")),
    };
    match result {
        Ok((code, regex)) => (Some(code), regex),
        Err(reason) => {
            collector.push(class_name, path_seg, comp, &constraint.name, &reason);
            (None, None)
        }
    }
}

// ---------------------------------------------------------------------------
// Constraint generators
// ---------------------------------------------------------------------------

fn gen_required(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    let condition = if attr.is_list {
        format!("{accessor}.is_empty()")
    } else if attr.is_primitive || attr.is_cim_datatype {
        match attr.lang_type.as_str() {
            "String" => format!("{accessor}.is_empty()"),
            "bool" | "i64" | "f64" => format!("{accessor}.is_none()"),
            _ => format!("{accessor}.is_empty()"),
        }
    } else if attr.is_enum_value {
        format!("{accessor}.is_none()")
    } else {
        format!("{accessor}.is_none()")
    };
    Ok((build_fn(fn_name, class_name, None, None, &condition, c, attr), None))
}

fn gen_max_count_one(
    fn_name: &str,
    class_name: &str,
    attr_id: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    let max = c.payload.get("maxCount").and_then(|v| v.as_int()).unwrap_or(1);
    if max != 1 {
        return Err(format!("sh:MaxCount={max} on non-list field (only maxCount=1 is supported)"));
    }
    if attr.is_list {
        return Err("sh:MaxCount=1 on list field — use sh:ExactCount instead".to_string());
    }
    fn esc(s: &str) -> String { s.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop = &attr.id;

    let mut s = String::new();
    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        if dataset.entries[mrid].block.duplicate_fields.contains(\"{attr_id}\") {{").unwrap();
    writeln!(s, "            violations.push(Violation {{").unwrap();
    writeln!(s, "                object_id:   mrid.clone(),").unwrap();
    writeln!(s, "                rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                class:       \"{class_name}\".to_string(),").unwrap();
    writeln!(s, "                property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "                message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "                severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "                name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "            }});").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    Ok((s, None))
}

fn gen_exact_count(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    if !attr.is_list {
        return Err("sh:ExactCount on non-list field".to_string());
    }
    let n = c.payload.get("minCount").and_then(|v| v.as_int()).unwrap_or(1);
    let condition = format!("{accessor}.len() != {n}");
    Ok((build_fn(fn_name, class_name, None, None, &condition, c, attr), None))
}

fn gen_in(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    if attr.is_list {
        if (attr.is_primitive || attr.is_cim_datatype) && attr.lang_type == "String" {
            return gen_slice_string_in(fn_name, class_name, accessor, attr, c);
        }
        return Err("sh:In on non-string list field".to_string());
    }
    if (attr.is_primitive || attr.is_cim_datatype) && attr.lang_type != "String" {
        return Err(format!("sh:In on non-string primitive field ({})", attr.lang_type));
    }
    let values = match c.payload.get("in").and_then(|v| v.as_list()) {
        Some(v) if !v.is_empty() => v,
        _ => return Err("sh:In: empty payload".to_string()),
    };

    let allowed_items: Vec<String> = values
        .iter()
        .map(|v| format!("\"{}\"", v.replace('"', "\\\"")))
        .collect();
    let allowed_str = allowed_items.join(", ");

    let (field_expr, guard) = field_expr_and_guard(accessor, attr);
    let prelude = format!("    const ALLOWED: &[&str] = &[{allowed_str}];\n");
    let condition = format!("!ALLOWED.contains(&{field_expr})");

    Ok((build_fn(fn_name, class_name, guard.as_deref(), Some(&prelude), &condition, c, attr), None))
}

fn gen_has_value(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    if attr.is_list { return Err("sh:HasValue on list field".to_string()); }
    if (attr.is_primitive || attr.is_cim_datatype) && attr.lang_type != "String" {
        return Err(format!("sh:HasValue on non-string primitive field ({})", attr.lang_type));
    }
    let expected = match c.payload.get("hasValue").and_then(|v| v.as_str()) {
        Some(v) => v.to_string(),
        None => return Err("sh:HasValue: missing payload".to_string()),
    };
    let esc = expected.replace('"', "\\\"");

    let (condition, guard) = if attr.is_enum_value {
        (format!("{accessor}.as_ref().map_or(true, |u| u.uri != \"{esc}\")"), None)
    } else if attr.is_primitive || attr.is_cim_datatype {
        (format!("{accessor} != \"{esc}\""),
         Some(format!("if {accessor}.is_empty() {{ continue; }}")))
    } else {
        (format!("{accessor}.as_ref().map_or(true, |r| r.mrid != \"{esc}\")"), None)
    };

    Ok((build_fn(fn_name, class_name, guard.as_deref(), None, &condition, c, attr), None))
}

fn gen_datatype(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    if attr.lang_type != "String" {
        return Err(format!("sh:Datatype on non-string field ({})", attr.lang_type));
    }
    let dt = c.payload.get("datatype").and_then(|v| v.as_str()).unwrap_or("");
    let check_fn = match dt {
        "xsd:dateTime" | "<http://www.w3.org/2001/XMLSchema#dateTime>" => "is_xsd_datetime",
        "xsd:date" | "<http://www.w3.org/2001/XMLSchema#date>" => "is_xsd_date",
        "xsd:gMonthDay" | "<http://www.w3.org/2001/XMLSchema#gMonthDay>" => "is_xsd_gmonthday",
        "xsd:anyURI" | "<http://www.w3.org/2001/XMLSchema#anyURI>" => "is_xsd_anyuri",
        _ => return Err(format!("sh:Datatype: unsupported datatype {:?}", dt)),
    };
    let guard = format!("if {accessor}.is_empty() {{ continue; }}");
    let condition = format!("!{check_fn}(&{accessor})");
    Ok((build_fn(fn_name, class_name, Some(&guard), None, &condition, c, attr), None))
}

fn gen_pattern(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
    regex_counter: &mut usize,
) -> Result<(String, Option<String>), String> {
    if attr.lang_type != "String" {
        return Err(format!("sh:Pattern on non-string field ({})", attr.lang_type));
    }
    let pattern = match c.payload.get("pattern").and_then(|v| v.as_str()) {
        Some(p) => p.to_string(),
        None => return Err("sh:Pattern: missing pattern payload".to_string()),
    };
    let idx = *regex_counter;
    *regex_counter += 1;
    let static_name = format!("REGEX_{idx}");
    let escaped = pattern.replace('\\', "\\\\").replace('"', "\\\"");
    let regex_decl = format!(
        "static {static_name}: LazyLock<regex::Regex> = LazyLock::new(|| regex::Regex::new(\"{escaped}\").expect(\"SHACL regex\"));\n"
    );
    let guard = format!("if {accessor}.is_empty() {{ continue; }}");
    let condition = format!("!{static_name}.is_match(&{accessor})");
    Ok((build_fn(fn_name, class_name, Some(&guard), None, &condition, c, attr), Some(regex_decl)))
}

fn gen_length(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
    is_min: bool,
) -> Result<(String, Option<String>), String> {
    if attr.lang_type != "String" {
        return Err(format!("sh:Length on non-string field ({})", attr.lang_type));
    }
    let key = if is_min { "minLength" } else { "maxLength" };
    let n = match c.payload.get(key).and_then(|v| v.as_int()) {
        Some(n) => n,
        None => return Err("sh:Length: missing payload".to_string()),
    };
    let op = if is_min { "<" } else { ">" };
    let guard = format!("if {accessor}.is_empty() {{ continue; }}");
    let condition = format!("{accessor}.chars().count() {op} {n}");
    Ok((build_fn(fn_name, class_name, Some(&guard), None, &condition, c, attr), None))
}

fn gen_numeric_range(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    let comp = c.component.as_str();
    let (key, op) = match comp {
        "sh:MinExclusiveConstraintComponent" => ("minExclusive", "<="),
        "sh:MaxExclusiveConstraintComponent" => ("maxExclusive", ">="),
        "sh:MinInclusiveConstraintComponent" => ("minInclusive", "<"),
        "sh:MaxInclusiveConstraintComponent" => ("maxInclusive", ">"),
        _ => return Err(format!("unknown numeric range component: {comp}")),
    };
    let val = match c.payload.get(key).and_then(|v| v.as_float()) {
        Some(f) => f,
        None => return Err("sh:NumericRange: missing payload".to_string()),
    };
    let (guard, condition) = match attr.lang_type.as_str() {
        "f64" => (
            format!("if {accessor}.is_none() {{ continue; }}"),
            format!("{accessor}.unwrap() {op} {val}_f64"),
        ),
        "i64" => (
            format!("if {accessor}.is_none() {{ continue; }}"),
            format!("({accessor}.unwrap() as f64) {op} {val}_f64"),
        ),
        _ => return Err(format!("sh:NumericRange on non-numeric field ({})", attr.lang_type)),
    };
    Ok((build_fn(fn_name, class_name, Some(&guard), None, &condition, c, attr), None))
}

fn gen_less_than(
    fn_name: &str,
    class_name: &str,
    spec: &CimSpecification,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    if !matches!(attr.lang_type.as_str(), "f64" | "i64") {
        return Err(format!("sh:LessThan on non-numeric field ({})", attr.lang_type));
    }
    let other_iri = match c.payload.get("lessThan").and_then(|v| v.as_str()) {
        Some(v) => v.to_string(),
        None => return Err("sh:LessThan: missing lessThan payload".to_string()),
    };
    let other_attr_id = local_name(&other_iri);
    let (other_prefix, other_attr) = match find_attr_in_hierarchy(spec, class_name, &other_attr_id) {
        Some(p) => p,
        None => return Err(format!("sh:LessThan: other attribute {} not found in hierarchy", other_attr_id)),
    };
    if !matches!(other_attr.lang_type.as_str(), "f64" | "i64") {
        return Err(format!("sh:LessThan: other attribute {} is non-numeric ({})", other_attr_id, other_attr.lang_type));
    }
    let other_field = sanitize_field(to_snake_case(&other_attr.label));
    let other_accessor = format!("{other_prefix}.{other_field}");

    let mut s = String::new();
    fn esc(x: &str) -> String { x.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop = &attr.id;

    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
    writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
    writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
    writeln!(s, "            Some(o) => o, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();
    writeln!(s, "        if {accessor}.is_none() || {other_accessor}.is_none() {{ continue; }}").unwrap();
    writeln!(s, "        if !(({accessor}.unwrap() as f64) < {other_accessor}.unwrap() as f64) {{").unwrap();
    writeln!(s, "            violations.push(Violation {{").unwrap();
    writeln!(s, "                object_id:   mrid.clone(),").unwrap();
    writeln!(s, "                rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                class:       \"{class_name}\".to_string(),").unwrap();
    writeln!(s, "                property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "                message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "                severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "                name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "            }});").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    Ok((s, None))
}

fn gen_not_class(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    if attr.is_primitive || attr.is_cim_datatype || attr.is_enum_value || attr.is_list {
        return Err("sh:NotClass on non-association field".to_string());
    }
    let forbidden = match c.payload.get("class").and_then(|v| v.as_str()) {
        Some(v) => local_name(v),
        None => return Err("sh:NotClass: missing class payload".to_string()),
    };

    let mut s = String::new();
    fn esc(x: &str) -> String { x.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop = &attr.id;

    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
    writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
    writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
    writeln!(s, "            Some(o) => o, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();
    writeln!(s, "        let ref_mrid = match {accessor}.as_ref() {{").unwrap();
    writeln!(s, "            Some(r) => &r.mrid, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();
    writeln!(s, "        if let Some(ref_entry) = dataset.entries.get(ref_mrid) {{").unwrap();
    writeln!(s, "            if ref_entry.element.type_name() == \"{forbidden}\" {{").unwrap();
    writeln!(s, "                violations.push(Violation {{").unwrap();
    writeln!(s, "                    object_id:   mrid.clone(),").unwrap();
    writeln!(s, "                    rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                    class:       \"{class_name}\".to_string(),").unwrap();
    writeln!(s, "                    property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "                    message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "                    severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "                    name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                    description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "                }});").unwrap();
    writeln!(s, "            }}").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    Ok((s, None))
}

fn gen_class(
    fn_name: &str,
    class_name: &str,
    spec: &CimSpecification,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    if attr.is_primitive || attr.is_cim_datatype || attr.is_enum_value {
        return Err("sh:Class on non-association field".to_string());
    }
    let wanted = match c.payload.get("class").and_then(|v| v.as_str()) {
        Some(v) => local_name(v),
        None => return Err("sh:Class: missing class payload".to_string()),
    };
    // Expand to all types that ARE or inherit from `wanted`. If everything
    // qualifies, the constraint is vacuously true and can be skipped.
    let allowed_types = class_and_subclasses(spec, &wanted);
    if allowed_types.is_empty() || allowed_types.len() >= spec.types.len() {
        return Err(format!("sh:Class vacuously true: all subtypes of {} qualify", wanted));
    }
    gen_ref_type_check(fn_name, class_name, accessor, attr, c, &allowed_types)
}

fn gen_or_class(
    fn_name: &str,
    class_name: &str,
    spec: &CimSpecification,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    if attr.is_primitive || attr.is_cim_datatype || attr.is_enum_value {
        return Err("sh:OrClass on non-association field".to_string());
    }
    let raw_classes: Vec<String> = match c.payload.get("classes").and_then(|v| v.as_list()) {
        Some(v) if !v.is_empty() => v.iter().map(|s| local_name(s)).collect(),
        _ => return Err("sh:OrClass: empty class list".to_string()),
    };
    // Expand each listed class to include its subclasses.
    let mut allowed_set = std::collections::BTreeSet::new();
    for cls in &raw_classes {
        for t in class_and_subclasses(spec, cls) {
            allowed_set.insert(t);
        }
    }
    let allowed_types: Vec<String> = allowed_set.into_iter().collect();
    if allowed_types.is_empty() || allowed_types.len() >= spec.types.len() {
        return Err("sh:OrClass vacuously true: all subtypes qualify".to_string());
    }
    gen_ref_type_check(fn_name, class_name, accessor, attr, c, &allowed_types)
}

fn gen_ref_type_check(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
    allowed_types: &[String],
) -> Result<(String, Option<String>), String> {
    fn esc(x: &str) -> String { x.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop = &attr.id;
    let allowed_str = allowed_types.iter()
        .map(|t| format!("\"{}\"", t))
        .collect::<Vec<_>>()
        .join(", ");

    let mut s = String::new();
    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
    writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
    writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
    writeln!(s, "            Some(o) => o, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();

    if attr.is_list {
        writeln!(s, "        for r in &{accessor} {{").unwrap();
        writeln!(s, "            let ref_id = r.mrid.trim_start_matches('#');").unwrap();
        writeln!(s, "            if ref_id.is_empty() {{ continue; }}").unwrap();
        writeln!(s, "            if let Some(ref_entry) = dataset.entries.get(ref_id) {{").unwrap();
        writeln!(s, "                let allowed: &[&str] = &[{allowed_str}];").unwrap();
        writeln!(s, "                if !allowed.contains(&ref_entry.element.type_name()) {{").unwrap();
        writeln!(s, "                    violations.push(Violation {{").unwrap();
        writeln!(s, "                        object_id:   mrid.clone(),").unwrap();
        writeln!(s, "                        rule_id:     \"{name_str}\".to_string(),").unwrap();
        writeln!(s, "                        class:       \"{class_name}\".to_string(),").unwrap();
        writeln!(s, "                        property:    \"{prop}\".to_string(),").unwrap();
        writeln!(s, "                        message:     \"{message}\".to_string(),").unwrap();
        writeln!(s, "                        severity:    \"{severity}\".to_string(),").unwrap();
        writeln!(s, "                        name:        \"{name_str}\".to_string(),").unwrap();
        writeln!(s, "                        description: \"{desc_str}\".to_string(),").unwrap();
        writeln!(s, "                    }});").unwrap();
        writeln!(s, "                }}").unwrap();
        writeln!(s, "            }}").unwrap();
        writeln!(s, "        }}").unwrap();
    } else {
        writeln!(s, "        let ref_mrid = match {accessor}.as_ref() {{").unwrap();
        writeln!(s, "            Some(r) => r.mrid.trim_start_matches('#'), None => continue,").unwrap();
        writeln!(s, "        }};").unwrap();
        writeln!(s, "        if let Some(ref_entry) = dataset.entries.get(ref_mrid) {{").unwrap();
        writeln!(s, "            let allowed: &[&str] = &[{allowed_str}];").unwrap();
        writeln!(s, "            if !allowed.contains(&ref_entry.element.type_name()) {{").unwrap();
        writeln!(s, "                violations.push(Violation {{").unwrap();
        writeln!(s, "                    object_id:   mrid.clone(),").unwrap();
        writeln!(s, "                    rule_id:     \"{name_str}\".to_string(),").unwrap();
        writeln!(s, "                    class:       \"{class_name}\".to_string(),").unwrap();
        writeln!(s, "                    property:    \"{prop}\".to_string(),").unwrap();
        writeln!(s, "                    message:     \"{message}\".to_string(),").unwrap();
        writeln!(s, "                    severity:    \"{severity}\".to_string(),").unwrap();
        writeln!(s, "                    name:        \"{name_str}\".to_string(),").unwrap();
        writeln!(s, "                    description: \"{desc_str}\".to_string(),").unwrap();
        writeln!(s, "                }});").unwrap();
        writeln!(s, "            }}").unwrap();
        writeln!(s, "        }}").unwrap();
    }

    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    Ok((s, None))
}

fn gen_slice_mrid_rdf_type_check(
    fn_name: &str,
    class_name: &str,
    spec: &CimSpecification,
    attr_id: &str,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    let (accessor_prefix, attr) = match find_attr_in_hierarchy(spec, class_name, attr_id) {
        Some(p) => p,
        None => return Err(format!("slice-mrid: attribute {} not found in hierarchy", attr_id)),
    };
    if !attr.is_list || attr.is_primitive || attr.is_cim_datatype || attr.is_enum_value || !attr.is_association_used {
        return Err("slice-mrid: field is not a usable list of associations".to_string());
    }
    let field_name = sanitize_field(to_snake_case(&attr.label));
    let accessor = format!("{accessor_prefix}.{field_name}");

    let comp = c.component.as_str();
    let allowed_types: Vec<String> = match comp {
        "sh:InConstraintComponent" => {
            match c.payload.get("in").and_then(|v| v.as_list()) {
                Some(v) if !v.is_empty() => v.iter().map(|s| local_name(s)).collect(),
                _ => return Err("slice-mrid sh:In: empty payload".to_string()),
            }
        }
        "sh:HasValueConstraintComponent" => {
            match c.payload.get("hasValue").and_then(|v| v.as_str()) {
                Some(v) => vec![local_name(v)],
                None => return Err("slice-mrid sh:HasValue: missing payload".to_string()),
            }
        }
        _ => return Err(format!("slice-mrid: component {} not supported", comp)),
    };
    if allowed_types.is_empty() {
        return Err("slice-mrid: empty allowed types list".to_string());
    }
    let allowed_str = allowed_types.iter()
        .map(|t| format!("\"{t}\""))
        .collect::<Vec<_>>()
        .join(", ");

    fn esc(x: &str) -> String { x.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop = &attr.id;

    let mut s = String::new();
    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
    writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
    writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
    writeln!(s, "            Some(o) => o, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();
    writeln!(s, "        for r in &{accessor} {{").unwrap();
    writeln!(s, "            let ref_id = r.mrid.trim_start_matches('#');").unwrap();
    writeln!(s, "            if ref_id.is_empty() {{ continue; }}").unwrap();
    writeln!(s, "            if let Some(ref_entry) = dataset.entries.get(ref_id) {{").unwrap();
    writeln!(s, "                let allowed: &[&str] = &[{allowed_str}];").unwrap();
    writeln!(s, "                if !allowed.contains(&ref_entry.element.type_name()) {{").unwrap();
    writeln!(s, "                    violations.push(Violation {{").unwrap();
    writeln!(s, "                        object_id:   mrid.clone(),").unwrap();
    writeln!(s, "                        rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                        class:       \"{class_name}\".to_string(),").unwrap();
    writeln!(s, "                        property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "                        message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "                        severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "                        name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                        description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "                    }});").unwrap();
    writeln!(s, "                }}").unwrap();
    writeln!(s, "            }}").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    Ok((s, None))
}

fn gen_slice_string_in(
    fn_name: &str,
    class_name: &str,
    accessor: &str,
    attr: &CimAttribute,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    let values = match c.payload.get("in").and_then(|v| v.as_list()) {
        Some(v) if !v.is_empty() => v,
        _ => return Err("sh:SliceStringIn: empty list".to_string()),
    };
    let allowed_items: Vec<String> = values
        .iter()
        .map(|v| format!("\"{}\"", v.replace('"', "\\\"")))
        .collect();
    let allowed_str = allowed_items.join(", ");

    fn esc(x: &str) -> String { x.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop = &attr.id;

    let mut s = String::new();
    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
    writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
    writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
    writeln!(s, "            Some(o) => o, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();
    writeln!(s, "        let allowed: &[&str] = &[{allowed_str}];").unwrap();
    writeln!(s, "        for val in &{accessor} {{").unwrap();
    writeln!(s, "            if val.is_empty() {{ continue; }}").unwrap();
    writeln!(s, "            if !allowed.contains(&val.as_str()) {{").unwrap();
    writeln!(s, "                violations.push(Violation {{").unwrap();
    writeln!(s, "                    object_id:   mrid.clone(),").unwrap();
    writeln!(s, "                    rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                    class:       \"{class_name}\".to_string(),").unwrap();
    writeln!(s, "                    property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "                    message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "                    severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "                    name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                    description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "                }});").unwrap();
    writeln!(s, "            }}").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    Ok((s, None))
}

// ---------------------------------------------------------------------------
// Inverse path generator
// ---------------------------------------------------------------------------

fn gen_inverse_count(
    fn_name: &str,
    target_class: &str,
    forward_pred: &str,
    spec: &CimSpecification,
    c: &ConstraintInfo,
) -> Result<(String, Option<String>), String> {
    let local = local_name(forward_pred);
    let (src_class, src_prop) = match local.split_once('.') {
        Some(p) => p,
        None => return Err("inverse path has no class.prop shape".to_string()),
    };

    let (obj_prefix, attr) = match find_attr_in_hierarchy(spec, src_class, &local) {
        Some(p) => p,
        None => return Err(format!("inverse attribute {} not found in hierarchy", local)),
    };
    if !attr.is_association_used {
        return Err("inverse unused association".to_string());
    }
    // Inverse path requires an association field (Option<MridRef> or Vec<MridRef>)
    if attr.is_primitive || attr.is_cim_datatype || attr.is_enum_value {
        return Err("inverse path on non-association field".to_string());
    }

    let field_name = sanitize_field(to_snake_case(src_prop));
    let src_prefix = obj_prefix.replacen("obj", "src", 1);
    let src_field  = format!("{src_prefix}.{field_name}");

    let index_snippet = if attr.is_list {
        format!("for r in &{src_field} {{ *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }}")
    } else {
        format!("if let Some(r) = &{src_field} {{ *ref_counts.entry(r.mrid.as_str()).or_insert(0) += 1; }}")
    };

    let (op, threshold) = match c.component.as_str() {
        "sh:MinCountConstraintComponent" | "sh:RequiredConstraintComponent" =>
            ("<", c.payload.get("minCount").and_then(|v| v.as_int()).unwrap_or(1)),
        "sh:MaxCountConstraintComponent" =>
            (">", c.payload.get("maxCount").and_then(|v| v.as_int()).unwrap_or(1)),
        _ => return Err(format!("inverse path: component {} not supported", c.component)),
    };

    Ok((build_inverse_fn(fn_name, target_class, src_class, &index_snippet, threshold, op, c), None))
}

fn build_inverse_fn(
    fn_name: &str,
    target_class: &str,
    src_class: &str,
    index_snippet: &str,
    threshold: i64,
    op: &str,
    c: &ConstraintInfo,
) -> String {
    let mut s = String::new();
    fn esc(x: &str) -> String { x.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop     = &c.name;

    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut ref_counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();").unwrap();
    writeln!(s, "    for src_mrid in dataset.by_type.get(\"{src_class}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        if let Some(src) = dataset.entries.get(src_mrid)").unwrap();
    writeln!(s, "            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::{src_class}>()) {{").unwrap();
    writeln!(s, "            {index_snippet}").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{target_class}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let count = ref_counts.get(mrid.as_str()).copied().unwrap_or(0);").unwrap();
    writeln!(s, "        if count {op} {threshold} {{").unwrap();
    writeln!(s, "            violations.push(Violation {{").unwrap();
    writeln!(s, "                object_id:   mrid.clone(),").unwrap();
    writeln!(s, "                rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                class:       \"{target_class}\".to_string(),").unwrap();
    writeln!(s, "                property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "                message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "                severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "                name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "            }});").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    s
}

// ---------------------------------------------------------------------------
// Code-building helpers
// ---------------------------------------------------------------------------

fn field_expr_and_guard(accessor: &str, attr: &CimAttribute) -> (String, Option<String>) {
    if attr.is_enum_value {
        (
            format!("{accessor}.as_ref().map_or(\"\", |u| u.uri.as_str())"),
            Some(format!("if {accessor}.is_none() {{ continue; }}")),
        )
    } else if attr.is_primitive || attr.is_cim_datatype {
        (
            format!("{accessor}.as_str()"),
            Some(format!("if {accessor}.is_empty() {{ continue; }}")),
        )
    } else {
        (
            format!("{accessor}.as_ref().map_or(\"\", |r| r.mrid.as_str())"),
            Some(format!("if {accessor}.is_none() {{ continue; }}")),
        )
    }
}

fn build_fn(
    fn_name: &str,
    class_name: &str,
    guard: Option<&str>,
    prelude: Option<&str>,     // constant decls outside the loop
    condition: &str,
    c: &ConstraintInfo,
    attr: &CimAttribute,
) -> String {
    let mut s = String::new();
    let prop = &attr.id;
    fn esc(s: &str) -> String { s.replace('\\', "\\\\").replace('"', "\\\"") }
    let message = esc(&c.message);
    let severity = &c.severity;
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);

    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    // Prelude goes BEFORE the loop (constants, regex etc.)
    if let Some(pre) = prelude {
        s.push_str(pre);
    }
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
    writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
    writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
    writeln!(s, "            Some(o) => o, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();
    if let Some(g) = guard {
        writeln!(s, "        {g}").unwrap();
    }
    writeln!(s, "        if {condition} {{").unwrap();
    writeln!(s, "            violations.push(Violation {{").unwrap();
    writeln!(s, "                object_id:   mrid.clone(),").unwrap();
    writeln!(s, "                rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                class:       \"{class_name}\".to_string(),").unwrap();
    writeln!(s, "                property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "                message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "                severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "                name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "                description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "            }});").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    s
}

// ---------------------------------------------------------------------------
// Field lookup
// ---------------------------------------------------------------------------

fn find_attr_in_hierarchy(
    spec: &CimSpecification,
    class_name: &str,
    attr_id: &str,
) -> Option<(String, CimAttribute)> {
    let mut depth = 0usize;
    let mut current_id = class_name.to_string();
    loop {
        let t = spec.types.get(&current_id)?;
        if let Some(attr) = t.attributes.iter().find(|a| a.id == attr_id) {
            // depth 0 → "obj", depth 1 → "obj.base", depth 2 → "obj.base.base"
            let prefix = format!("obj{}", ".base".repeat(depth));
            return Some((prefix, attr.clone()));
        }
        if t.super_type.is_empty() || t.super_type == current_id {
            break;
        }
        depth += 1;
        current_id = t.super_type.clone();
    }
    None
}

// ---------------------------------------------------------------------------
// Name helpers
// ---------------------------------------------------------------------------

fn local_name(simplified_iri: &str) -> String {
    if let Some(colon) = simplified_iri.find(':') {
        simplified_iri[colon + 1..].to_string()
    } else {
        simplified_iri.to_string()
    }
}

/// Convert a TTL file name to a valid Rust module name.
fn file_to_mod_name(file_name: &str) -> String {
    let raw: String = file_name
        .chars()
        .map(|c| if c.is_alphanumeric() { c.to_ascii_lowercase() } else { '_' })
        .collect();
    // Module names can't start with a digit
    let raw = raw.trim_matches('_');
    if raw.starts_with(|c: char| c.is_ascii_digit()) {
        format!("p{raw}")
    } else {
        raw.to_string()
    }
}

fn component_suffix(component: &str) -> &str {
    match component {
        "sh:RequiredConstraintComponent" => "required",
        "sh:MinCountConstraintComponent" => "min_count",
        "sh:MaxCountConstraintComponent" => "max_count",
        "sh:ExactCountConstraintComponent" => "exact_count",
        "sh:InConstraintComponent" => "in",
        "sh:HasValueConstraintComponent" => "has_value",
        "sh:DatatypeConstraintComponent" => "datatype",
        "sh:ClassConstraintComponent" => "class_check",
        "sh:OrClassConstraintComponent" => "or_class",
        "sh:NotClassConstraintComponent" => "not_class",
        "sh:LessThanConstraintComponent" => "less_than",
        "sh:PatternConstraintComponent" => "pattern",
        "sh:MinLengthConstraintComponent" => "min_length",
        "sh:MaxLengthConstraintComponent" => "max_length",
        "sh:MinExclusiveConstraintComponent" => "min_excl",
        "sh:MaxExclusiveConstraintComponent" => "max_excl",
        "sh:MinInclusiveConstraintComponent" => "min_incl",
        "sh:MaxInclusiveConstraintComponent" => "max_incl",
        _ => "constraint",
    }
}

fn safe_fn_name(raw: &str) -> String {
    // Collapse runs of underscores, ensure doesn't start with digit
    let collapsed: String = {
        let mut prev = '_';
        let mut s = String::new();
        for c in raw.chars() {
            if c == '_' && prev == '_' { continue; }
            s.push(c);
            prev = c;
        }
        s.trim_matches('_').to_string()
    };
    if collapsed.starts_with(|c: char| c.is_ascii_digit()) {
        format!("check_{collapsed}")
    } else if collapsed.len() > 100 {
        format!("{}_etc", collapsed[..97].trim_end_matches('_'))
    } else {
        collapsed
    }
}

fn extract_fn_name(code: &str) -> String {
    code.lines()
        .find(|l| l.starts_with("pub fn "))
        .and_then(|l| l.strip_prefix("pub fn "))
        .and_then(|l| l.split('(').next())
        .unwrap_or("")
        .to_string()
}

// ---------------------------------------------------------------------------
// Compound constraint generators (sh:xone, sh:or, sh:and)
// ---------------------------------------------------------------------------

fn gen_compound_check(
    file_snake: &str,
    class_name: &str,
    spec: &CimSpecification,
    c: &ConstraintInfo,
) -> Result<String, String> {
    let branches = c.payload.get("branches").and_then(|v| v.as_shapes())
        .ok_or_else(|| "compound check: missing branches payload".to_string())?;

    let comp_suffix = match c.component.as_str() {
        "sh:XoneConstraintComponent" => "xone",
        "sh:OrConstraintComponent" => "or",
        "sh:AndConstraintComponent" => "and",
        _ => return Err(format!("unknown compound component: {}", c.component)),
    };
    let raw_name = format!(
        "check_{file_snake}_{class_snake}_{comp_suffix}",
        class_snake = to_snake_case(class_name),
    );
    let fn_name = safe_fn_name(&raw_name);

    match c.component.as_str() {
        "sh:XoneConstraintComponent" => gen_xone_check(&fn_name, class_name, spec, c, branches)
            .ok_or_else(|| "sh:xone: branch structure not supported".to_string()),
        "sh:OrConstraintComponent"   => gen_or_compound_check(&fn_name, class_name, spec, c, branches)
            .ok_or_else(|| "sh:or: branch structure not supported".to_string()),
        "sh:AndConstraintComponent"  => gen_and_compound_check(&fn_name, class_name, spec, c, branches)
            .ok_or_else(|| "sh:and: branch structure not supported".to_string()),
        _ => Err(format!("unknown compound component: {}", c.component)),
    }
}

/// sh:xone: exactly one of N forward-pointer fields must be non-None.
/// Each branch must have a single MinCount=1 on a forward association path.
fn gen_xone_check(
    fn_name: &str,
    class_name: &str,
    spec: &CimSpecification,
    c: &ConstraintInfo,
    branches: &[Vec<ConstraintInfo>],
) -> Option<String> {
    let mut field_accessors: Vec<String> = Vec::new();
    for branch in branches {
        let min1 = branch.iter().find(|ci|
            ci.component == "sh:MinCountConstraintComponent"
            && ci.payload.get("minCount").and_then(|v| v.as_int()) == Some(1)
            && ci.path.len() == 1 && !ci.path[0].starts_with('~'))?;
        let attr_id = local_name(&min1.path[0]);
        let (acc_prefix, attr) = find_attr_in_hierarchy(spec, class_name, &attr_id)?;
        if !attr.is_association_used || attr.is_list { return None; }
        let field = sanitize_field(to_snake_case(&attr.label));
        field_accessors.push(format!("{acc_prefix}.{field}"));
    }
    if field_accessors.len() < 2 { return None; }

    let (message, severity, name_str, desc_str, prop) = extract_violation_fields(c);
    let mut s = String::new();
    write_fn_header(&mut s, fn_name, class_name);
    writeln!(s, "        let mut pass_count = 0usize;").unwrap();
    for acc in &field_accessors {
        writeln!(s, "        if {acc}.is_some() {{ pass_count += 1; }}").unwrap();
    }
    writeln!(s, "        if pass_count != 1 {{").unwrap();
    write_violation(&mut s, class_name, &prop, &message, &severity, &name_str, &desc_str, "            ");
    writeln!(s, "        }}").unwrap();
    write_fn_footer(&mut s);
    Some(s)
}

/// sh:or: violation when ALL branches fail their inverse-count range.
/// Each branch must have exactly one inverse-path with min/max count.
fn gen_or_compound_check(
    fn_name: &str,
    class_name: &str,
    spec: &CimSpecification,
    c: &ConstraintInfo,
    branches: &[Vec<ConstraintInfo>],
) -> Option<String> {
    struct InvBranch { prelude: String, fail_cond: String }
    let mut parsed: Vec<InvBranch> = Vec::new();

    for (i, branch) in branches.iter().enumerate() {
        // Must have at least one constraint with inverse path
        let inv = branch.iter().find(|ci|
            !ci.path.is_empty() && ci.path[0].starts_with('~'))?;
        if inv.path.len() != 1 { return None; } // multi-segment: skip

        let prelude = build_inverse_count_prelude(spec, &inv.path[0], i)?;
        let min = branch.iter().find(|ci| ci.component == "sh:MinCountConstraintComponent")
            .and_then(|ci| ci.payload.get("minCount").and_then(|v| v.as_int()))
            .unwrap_or(0);
        let max = branch.iter().find(|ci| ci.component == "sh:MaxCountConstraintComponent")
            .and_then(|ci| ci.payload.get("maxCount").and_then(|v| v.as_int()))
            .unwrap_or(i64::MAX / 2);
        let fail_cond = inverse_fail_cond(i, min, max);
        parsed.push(InvBranch { prelude, fail_cond });
    }
    if parsed.len() < 2 { return None; }

    let (message, severity, name_str, desc_str, prop) = extract_violation_fields(c);
    let all_fail = parsed.iter().map(|b| b.fail_cond.as_str()).collect::<Vec<_>>().join(" && ");

    let mut s = String::new();
    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    for b in &parsed { s.push_str(&b.prelude); }
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        if {all_fail} {{").unwrap();
    write_violation(&mut s, class_name, &prop, &message, &severity, &name_str, &desc_str, "            ");
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    Some(s)
}

/// sh:and: violation when ANY branch fails.
/// Branches can be:
///   - forward MaxCount=0 (field must be absent)
///   - forward MinCount=1+MaxCount=1 (field must be present, scalar only)
///   - inverse single-segment path with min/max count
///   - multi-segment (skipped — returns None for whole check)
fn gen_and_compound_check(
    fn_name: &str,
    class_name: &str,
    spec: &CimSpecification,
    c: &ConstraintInfo,
    branches: &[Vec<ConstraintInfo>],
) -> Option<String> {
    let mut prelude_parts: Vec<String> = Vec::new();
    let mut fail_conds: Vec<String> = Vec::new();
    let mut needs_obj = false;
    let mut inv_idx = 0usize;

    for branch in branches {
        // Find a path from any constraint in this branch
        let any_path = branch.iter().find(|ci| !ci.path.is_empty()).map(|ci| &ci.path[0]);
        let path0 = any_path?;

        if path0.starts_with('~') {
            // Inverse path branch
            if branch.iter().any(|ci| ci.path.len() > 1) { return None; } // multi-seg: skip
            let inv_ci = branch.iter().find(|ci| !ci.path.is_empty())?;
            if inv_ci.path.len() != 1 { return None; }
            let prelude = build_inverse_count_prelude(spec, &inv_ci.path[0], inv_idx)?;
            let min = branch.iter().find(|ci| ci.component == "sh:MinCountConstraintComponent")
                .and_then(|ci| ci.payload.get("minCount").and_then(|v| v.as_int()))
                .unwrap_or(0);
            let max = branch.iter().find(|ci| ci.component == "sh:MaxCountConstraintComponent")
                .and_then(|ci| ci.payload.get("maxCount").and_then(|v| v.as_int()))
                .unwrap_or(i64::MAX / 2);
            prelude_parts.push(prelude);
            fail_conds.push(inverse_fail_cond(inv_idx, min, max));
            inv_idx += 1;
        } else {
            // Forward field branch — determine what kind
            if branch.iter().any(|ci| ci.path.len() > 1) { return None; } // multi-seg: skip
            let attr_id = local_name(path0);
            let (acc_prefix, attr) = find_attr_in_hierarchy(spec, class_name, &attr_id)?;
            let field = sanitize_field(to_snake_case(&attr.label));
            let accessor = format!("{acc_prefix}.{field}");

            let max = branch.iter().find(|ci| ci.component == "sh:MaxCountConstraintComponent")
                .and_then(|ci| ci.payload.get("maxCount").and_then(|v| v.as_int()));
            let min = branch.iter().find(|ci| ci.component == "sh:MinCountConstraintComponent")
                .and_then(|ci| ci.payload.get("minCount").and_then(|v| v.as_int()));

            let fail_cond = if max == Some(0) {
                // Field must be absent
                field_absent_cond(&attr, &accessor)?
            } else if min == Some(1) && (max == Some(1) || max.is_none()) {
                // Field must be present
                field_required_cond(&attr, &accessor)?
            } else {
                return None; // unsupported pattern
            };
            needs_obj = true;
            fail_conds.push(fail_cond);
        }
    }

    if fail_conds.is_empty() { return None; }
    let any_fail = fail_conds.join(" || ");

    let (message, severity, name_str, desc_str, prop) = extract_violation_fields(c);

    let mut s = String::new();
    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    for p in &prelude_parts { s.push_str(p); }
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    if needs_obj {
        writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
        writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
        writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
        writeln!(s, "            Some(o) => o, None => continue,").unwrap();
        writeln!(s, "        }};").unwrap();
    }
    writeln!(s, "        if {any_fail} {{").unwrap();
    write_violation(&mut s, class_name, &prop, &message, &severity, &name_str, &desc_str, "            ");
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
    Some(s)
}

// ---------------------------------------------------------------------------
// Compound generator helpers
// ---------------------------------------------------------------------------

/// Build the prelude code that counts inverse references for one branch.
/// `path0` is the raw inverse path segment like "~cim:Terminal.ConductingEquipment".
fn build_inverse_count_prelude(spec: &CimSpecification, path0: &str, idx: usize) -> Option<String> {
    let forward_pred = &path0[1..]; // strip leading '~'
    let local = local_name(forward_pred);
    let (src_class, _) = local.split_once('.')?;
    let (acc_prefix, attr) = find_attr_in_hierarchy(spec, src_class, &local)?;
    if !attr.is_association_used { return None; }
    let field = sanitize_field(to_snake_case(&attr.label));
    let src_prefix = acc_prefix.replacen("obj", "src", 1);
    let src_field = format!("{src_prefix}.{field}");

    let mut s = String::new();
    writeln!(s, "    let mut counts{idx}: std::collections::HashMap<String, usize> = std::collections::HashMap::new();").unwrap();
    writeln!(s, "    for src_mrid in dataset.by_type.get(\"{src_class}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        if let Some(src) = dataset.entries.get(src_mrid)").unwrap();
    writeln!(s, "            .and_then(|e| e.element.as_any().downcast_ref::<cimstructs::{src_class}>()) {{").unwrap();
    if attr.is_list {
        writeln!(s, "            for r in &{src_field} {{").unwrap();
        writeln!(s, "                *counts{idx}.entry(r.mrid.trim_start_matches('#').to_string()).or_insert(0) += 1;").unwrap();
        writeln!(s, "            }}").unwrap();
    } else {
        writeln!(s, "            if let Some(r) = &{src_field} {{").unwrap();
        writeln!(s, "                *counts{idx}.entry(r.mrid.trim_start_matches('#').to_string()).or_insert(0) += 1;").unwrap();
        writeln!(s, "            }}").unwrap();
    }
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    Some(s)
}

fn inverse_fail_cond(idx: usize, min: i64, max: i64) -> String {
    let count = format!("counts{idx}.get(mrid.as_str()).copied().unwrap_or(0)");
    if min == max {
        format!("{count} != {min}")
    } else if max == i64::MAX / 2 {
        format!("{count} < {min}")
    } else if min == 0 {
        format!("{count} > {max}")
    } else {
        format!("{{ let c = {count}; c < {min} || c > {max} }}")
    }
}

/// Violation condition for "field must be absent" (sh:maxCount 0).
fn field_absent_cond(attr: &CimAttribute, accessor: &str) -> Option<String> {
    if attr.is_list {
        Some(format!("!{accessor}.is_empty()"))
    } else if attr.is_primitive || attr.is_cim_datatype {
        Some(match attr.lang_type.as_str() {
            "String" => format!("!{accessor}.is_empty()"),
            _ => format!("{accessor}.is_some()"),  // Option<f64>, Option<i64>, Option<bool>
        })
    } else if attr.is_enum_value {
        Some(format!("{accessor}.is_some()"))
    } else {
        Some(format!("{accessor}.is_some()"))  // Option<MridRef>
    }
}

/// Violation condition for "field must be present" (sh:minCount 1 + maxCount 1).
fn field_required_cond(attr: &CimAttribute, accessor: &str) -> Option<String> {
    if attr.is_list {
        Some(format!("{accessor}.is_empty()"))
    } else if attr.is_primitive || attr.is_cim_datatype {
        Some(match attr.lang_type.as_str() {
            "String" => format!("{accessor}.is_empty()"),
            _ => format!("{accessor}.is_none()"),
        })
    } else if attr.is_enum_value {
        Some(format!("{accessor}.is_none()"))
    } else {
        Some(format!("{accessor}.is_none()"))
    }
}

fn extract_violation_fields(c: &ConstraintInfo) -> (String, String, String, String, String) {
    fn esc(x: &str) -> String { x.replace('\\', "\\\\").replace('"', "\\\"") }
    let message  = esc(&c.message);
    let severity = if c.severity.is_empty() { "sh:Violation".to_string() } else { c.severity.clone() };
    let name_str = esc(&c.name);
    let desc_str = esc(&c.description);
    let prop     = esc(&c.name);
    (message, severity, name_str, desc_str, prop)
}

fn write_fn_header(s: &mut String, fn_name: &str, class_name: &str) {
    writeln!(s, "pub fn {fn_name}(dataset: &CimDataset) -> Vec<Violation> {{").unwrap();
    writeln!(s, "    let mut violations = Vec::new();").unwrap();
    writeln!(s, "    for mrid in dataset.by_type.get(\"{class_name}\").into_iter().flatten() {{").unwrap();
    writeln!(s, "        let entry = &dataset.entries[mrid];").unwrap();
    writeln!(s, "        let obj = match entry.element.as_any()").unwrap();
    writeln!(s, "            .downcast_ref::<cimstructs::{class_name}>() {{").unwrap();
    writeln!(s, "            Some(o) => o, None => continue,").unwrap();
    writeln!(s, "        }};").unwrap();
}

fn write_fn_footer(s: &mut String) {
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    violations").unwrap();
    writeln!(s, "}}").unwrap();
}

fn write_violation(s: &mut String, class_name: &str, prop: &str, message: &str, severity: &str, name_str: &str, desc_str: &str, indent: &str) {
    writeln!(s, "{indent}violations.push(Violation {{").unwrap();
    writeln!(s, "{indent}    object_id:   mrid.clone(),").unwrap();
    writeln!(s, "{indent}    rule_id:     \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "{indent}    class:       \"{class_name}\".to_string(),").unwrap();
    writeln!(s, "{indent}    property:    \"{prop}\".to_string(),").unwrap();
    writeln!(s, "{indent}    message:     \"{message}\".to_string(),").unwrap();
    writeln!(s, "{indent}    severity:    \"{severity}\".to_string(),").unwrap();
    writeln!(s, "{indent}    name:        \"{name_str}\".to_string(),").unwrap();
    writeln!(s, "{indent}    description: \"{desc_str}\".to_string(),").unwrap();
    writeln!(s, "{indent}}});").unwrap();
}

fn dedup_fn_name(raw_name: String, used: &std::collections::HashSet<String>) -> String {
    if !used.contains(&raw_name) {
        return raw_name;
    }
    let mut n = 2usize;
    loop {
        let candidate = format!("{raw_name}_{n}");
        if !used.contains(&candidate) { return candidate; }
        n += 1;
    }
}

// ---------------------------------------------------------------------------
// Class hierarchy helpers
// ---------------------------------------------------------------------------

fn is_subtype_of(spec: &CimSpecification, type_name: &str, ancestor: &str) -> bool {
    let mut current = type_name.to_string();
    let mut visited = std::collections::HashSet::new();
    loop {
        if !visited.insert(current.clone()) {
            return false;
        }
        match spec.types.get(&current) {
            Some(t) => {
                if t.super_type.is_empty() || t.super_type == current {
                    return false;
                }
                if t.super_type == ancestor {
                    return true;
                }
                current = t.super_type.clone();
            }
            None => return false,
        }
    }
}

fn class_and_subclasses(spec: &CimSpecification, class: &str) -> Vec<String> {
    let mut result: Vec<String> = spec.types
        .keys()
        .filter(|name| name.as_str() == class || is_subtype_of(spec, name, class))
        .cloned()
        .collect();
    result.sort();
    result
}
