[package]
name = "cimoxide-py"
version = "0.1.0"
edition = "2024"

[lib]
name = "cimoxide"
crate-type = ["cdylib"]

[dependencies]
cimdecoder    = { path = "../cimdecoder" }
cimstructs    = { path = "../cimstructs" }
cimvalidation = { path = "../cimvalidation" }
pyo3          = { version = "0.25", features = ["extension-module"] }
pythonize     = "0.25"
