[package]
name = "cimoxide-convert"
description = "Conversion of CGMES datasets between RDF/XML and JSON"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories = ["science", "encoding"]
include = ["src/**/*.rs", "Cargo.toml"]

[lib]
name = "cimconvert"

[dependencies]
cimoxide-decoder = { workspace = true }
cimoxide-structs = { workspace = true }
serde_json  = "1"

[dev-dependencies]
cimoxide-decoder = { workspace = true }
