//! Emits the class table for a family represented as property bags.
//!
//! A bag family contributes data rows rather than Rust types, so adding one
//! costs a table instead of ~700 struct files, and two families declaring the
//! same class name is a non-event: the rows are keyed by namespace.

use std::fmt::Write;

use crate::schema::model::{CimAttribute, CimSpecification, CimType};

/// Class ids in emission order; the index of each is its `ClassId`.
fn ordered_ids(spec: &CimSpecification) -> Vec<&String> {
    let mut ids: Vec<&String> = spec.types.keys().collect();
    ids.sort();
    ids
}

fn attr_kind(a: &CimAttribute) -> &'static str {
    if a.is_enum_value {
        "AttrKind::Enum"
    } else if a.is_primitive || a.is_cim_datatype {
        "AttrKind::Literal"
    } else {
        "AttrKind::Association"
    }
}

fn attr_range(a: &CimAttribute) -> &str {
    if a.rdf_range.is_empty() {
        &a.cim_data_type
    } else {
        &a.rdf_range
    }
}

fn str_list(items: &[String]) -> String {
    let inner: Vec<String> = items.iter().map(|o| format!("\"{o}\"")).collect();
    format!("&[{}]", inner.join(", "))
}

pub fn render_classes(spec: &CimSpecification) -> String {
    let family = spec.family;
    let ids = ordered_ids(spec);
    let index_of: std::collections::HashMap<&str, usize> = ids
        .iter()
        .enumerate()
        .map(|(i, id)| (id.as_str(), i))
        .collect();

    let mut s = String::new();
    writeln!(s, "// Generated by cimgen — do not edit by hand.").unwrap();
    writeln!(s, "#![allow(clippy::all, dead_code)]").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "use crate::base::{{AttrDef, AttrKind, ClassDef}};").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "/// Every class of the `{}` family. The index of a row is its class id.",
        family.id
    )
    .unwrap();
    writeln!(s, "pub static CLASSES: &[ClassDef] = &[").unwrap();

    for id in &ids {
        let t: &CimType = &spec.types[*id];
        let super_class = index_of
            .get(t.super_type.as_str())
            .map(|i| format!("Some({i})"))
            .unwrap_or_else(|| "None".to_string());
        writeln!(s, "    ClassDef {{").unwrap();
        writeln!(s, "        ns: \"{}\",", t.namespace).unwrap();
        writeln!(s, "        local: \"{}\",", t.id).unwrap();
        writeln!(
            s,
            "        qualified: \"{}{}\",",
            family.type_prefix, t.id
        )
        .unwrap();
        writeln!(s, "        super_class: {super_class},").unwrap();
        writeln!(s, "        concrete: {},", !t.concrete_in.is_empty()).unwrap();
        writeln!(s, "        origins: {},", str_list(&t.origins)).unwrap();

        let attrs: Vec<&CimAttribute> = t
            .attributes
            .iter()
            .filter(|a| a.is_association_used)
            .collect();
        if attrs.is_empty() {
            writeln!(s, "        attrs: &[],").unwrap();
        } else {
            writeln!(s, "        attrs: &[").unwrap();
            for a in attrs {
                writeln!(
                    s,
                    "            AttrDef {{ id: \"{id}\", ns: \"{ns}\", kind: {kind}, range: \"{range}\", is_list: {is_list}, origins: {origins} }},",
                    id = a.id,
                    ns = a.namespace,
                    kind = attr_kind(a),
                    range = attr_range(a),
                    is_list = a.is_list,
                    origins = str_list(&a.origins),
                )
                .unwrap();
            }
            writeln!(s, "        ],").unwrap();
        }
        writeln!(s, "    }},").unwrap();
    }

    writeln!(s, "];").unwrap();
    s
}

/// `(namespace, local, qualified, parser)` rows dispatching to property bags.
pub fn registry_rows(spec: &CimSpecification) -> Vec<(String, String, String, String)> {
    let family = spec.family;
    ordered_ids(spec)
        .iter()
        .enumerate()
        .map(|(i, id)| {
            let t = &spec.types[*id];
            (
                t.namespace.clone(),
                t.id.clone(),
                format!("{}{}", family.type_prefix, t.id),
                format!(
                    "|b| Box::new(crate::base::GenericElement::from_block(&crate::{}_classes::CLASSES[{i}], b))",
                    family.id
                ),
            )
        })
        .collect()
}
